### ISSUE TITLE
Rotors stop moving when attached to another moving frame

### ISSUE THREAD

**Issue by SwapUNaph** [PX4/PX4-SITL_gazebo-classic#103]
Hi,
I am simulating a VTOL tiltrotor. I used the `standard_vtol` as a template to get started. I have attached a link called `shaft` to the `base_link`. The `shaft` link is getting control from channel 4 for tilt servo. Front rotors are attached to the `shaft`. Now when I use this setup the rotors stop rotating. Notably, when the control on `shaft` is removed the rotors start spinning.
Any suggestions on how to get both of them working?

**Comment by TSC21** [comment]
@SwapUNaph any updates on this?

**Comment by SwapUNaph** [comment]
I have done a hack.
Now I am passing the tilt angle to the model and calculating the component of force vector in the forward(X) as well as upward(Z) direction.

**Comment by RomanBapst** [comment]
@SwapUNaph I have pushed a tiltrotor model to PX4 with the same idea as how you described it above.
It took some time to get it working and I think I also had the same issue at some point. If I remember correctly it's not advisable to directly try to set the angle of a control joint but rather apply a moment to it and use a PID controller to control the angle.

**Comment by TSC21** [comment]
I think we can close this now as this as a solution was already found by @RomanBapst.
