### ISSUE TITLE
How to put two PX4 drones in Gazebo?

### ISSUE THREAD

**Issue by cnpcshangbo** [PX4/PX4-SITL_gazebo-classic#120]
Hello guys,
I have went through some tutorials to run a Gazebo simulation with a drone in it.
However, what I need is to have two drones in one Gazebo simulation and use two ROS to control it. In the control part I am going to use MATLAB Robotics System Toolbox to communicate with the two drones.
Anybody has some ideas on how to finish that two drone simulation?
Thanks,
@cnpcshangbo

**Comment by TSC21** [comment]
Solved in https://github.com/PX4/Firmware/pull/7235. Check devguide docs also on how to proceed.
