### ISSUE TITLE
build fail with gazebo_iris_opt_flow as target

### ISSUE THREAD

**Issue by ykhedar** [PX4/PX4-SITL_gazebo-classic#178]
I am using a slightly modified docker version of the `px4io/px4-dev-ros:v1.0`. The modification is just in terms of Nvidia driver installation. The docker was working fine a couple of weeks ago. Today when I cloned the Firmware repo again and tried to compile with `make posix_sitl_default`, it compiles fine but with gazebo as a target it gives error..

e.g. the command `make posix gazebo_iris_opt_flow` gives the following errors:

`/home/root/src/Firmware/Tools/sitl_gazebo/src/gazebo_irlock_plugin.cpp: In member function 'virtual void gazebo::IRLockPlugin::Load(gazebo::sensors::SensorPtr, sdf::ElementPtr)':
/home/root/src/Firmware/Tools/sitl_gazebo/src/gazebo_irlock_plugin.cpp:53:81: error: no matching function for call to 'dynamic_pointer_cast(gazebo::sensors::SensorPtr&)'
   this->camera = std::dynamic_pointer_cast<sensors::LogicalCameraSensor>(_sensor);
                                                                                 ^
/home/root/src/Firmware/Tools/sitl_gazebo/src/gazebo_irlock_plugin.cpp:53:81: note: candidates are:
In file included from /usr/include/c++/4.8/bits/shared_ptr.h:52:0,
                 from /usr/include/c++/4.8/memory:82,
                 from /usr/include/boost/smart_ptr/weak_ptr.hpp:16,
                 from /usr/include/boost/smart_ptr/enable_shared_from_this.hpp:16,
                 from /usr/include/boost/enable_shared_from_this.hpp:16,
                 from /usr/include/gazebo-6.6/gazebo/sensors/Sensor.hh:20,
                 from /usr/include/gazebo-6.6/gazebo/sensors/DepthCameraSensor.hh:22,
                 from /home/root/src/Firmware/Tools/sitl_gazebo/src/gazebo_irlock_plugin.cpp:23:
/usr/include/c++/4.8/bits/shared_ptr_base.h:1177:5: note: template<class _Tp, class _Tp1, __gnu_cxx::_Lock_policy _Lp> std::__shared_ptr<_Tp1, _Lp> std::dynamic_pointer_cast(const std::__shared_ptr<_Tp2, _Lp>&)
     dynamic_pointer_cast(const __shared_ptr<_Tp1, _Lp>& __r) noexcept
     ^
/usr/include/c++/4.8/bits/shared_ptr_base.h:1177:5: note:   template argument deduction/substitution failed:
/home/root/src/Firmware/Tools/sitl_gazebo/src/gazebo_irlock_plugin.cpp:53:81: note:   'gazebo::sensors::SensorPtr {aka boost::shared_ptr<gazebo::sensors::Sensor>}' is not derived from 'const std::__shared_ptr<_Tp2, _Lp>'
   this->camera = std::dynamic_pointer_cast<sensors::LogicalCameraSensor>(_sensor);
                                                                                 ^
In file included from /usr/include/c++/4.8/memory:82:0,
                 from /usr/include/boost/smart_ptr/weak_ptr.hpp:16,
                 from /usr/include/boost/smart_ptr/enable_shared_from_this.hpp:16,
                 from /usr/include/boost/enable_shared_from_this.hpp:16,
                 from /usr/include/gazebo-6.6/gazebo/sensors/Sensor.hh:20,
                 from /usr/include/gazebo-6.6/gazebo/sensors/DepthCameraSensor.hh:22,
                 from /home/root/src/Firmware/Tools/sitl_gazebo/src/gazebo_irlock_plugin.cpp:23:
/usr/include/c++/4.8/bits/shared_ptr.h:447:5: note: template<class _Tp, class _Tp1> std::shared_ptr<_Tp1> std::dynamic_pointer_cast(const std::shared_ptr<_Tp2>&)
     dynamic_pointer_cast(const shared_ptr<_Tp1>& __r) noexcept
     ^
/usr/include/c++/4.8/bits/shared_ptr.h:447:5: note:   template argument deduction/substitution failed:
/home/root/src/Firmware/Tools/sitl_gazebo/src/gazebo_irlock_plugin.cpp:53:81: note:   'gazebo::sensors::SensorPtr {aka boost::shared_ptr<gazebo::sensors::Sensor>}' is not derived from 'const std::shared_ptr<_Tp2>'
   this->camera = std::dynamic_pointer_cast<sensors::LogicalCameraSensor>(_sensor);
                                                                                 ^
/home/root/src/Firmware/Tools/sitl_gazebo/src/gazebo_irlock_plugin.cpp:68:38: error: 'class gazebo::sensors::Sensor' has no member named 'ParentName'
   const string scopedName = _sensor->ParentName();`

Could anyone point me in the right direction please. :)

Only change is regarding the host for the docker, I recently upgraded from Ubuntu 14.04 to 16.04 but I don't think that should make any difference.

Regards,

ykhedar

**Comment by TSC21** [comment]
@ykhedar is this still a problem to you?

**Comment by ykhedar** [comment]
Sorry i forgot to update. This is no longer a problem for me. Sadly I did not document my solution and do not recollect now :(.
