### ISSUE TITLE
Gazebo freezes with GStreamer plugin enabled 

### ISSUE THREAD

**Issue by mtbrobotanist** [PX4/PX4-SITL_gazebo-classic#182]
Hello,

I followed the gstreamer install and setup instructions from here: https://dev.px4.io/en/simulation/gazebo.html

everything built fine and libgazebo_video_stream_widget.so exists.

Next i added the gui xml tags to iris.world.

Then, running:
``` 
make posix_sitl_default gazebo
```
launches gazebo, but it freezes at the splash screen with gazebo only partially loaded.

**Comment by mtbrobotanist** [comment]
![gazebo_frozen](https://user-images.githubusercontent.com/8548986/35884112-61def4c4-0b3e-11e8-9d8e-b1654cf555a3.png)

**Comment by TSC21** [comment]
@mtbrobotanist still a problem?

**Comment by TSC21** [comment]
Closing as stale.
