### ISSUE TITLE
Vision plugin correct?

### ISSUE THREAD

**Issue by julianoes** [PX4/PX4-SITL_gazebo-classic#193]
I just stumbled upon this:

https://github.com/PX4/sitl_gazebo/blob/90c9e5db3f53b0d963a4f240cc712f2ecf246bc4/src/gazebo_vision_plugin.cpp#L133-L135

and was wondering if roll and pitch are swapped on purpose?
[gazebo::math::Quaternion::SetFromEuler](http://osrf-distributions.s3.amazonaws.com/gazebo/api/4.0.0/classgazebo_1_1math_1_1Quaternion.html#aed29d19853fde3fc2662974c44811346) has the ordering roll, pitch yaw.

@ChristophTobler @mrivi

**Comment by TSC21** [comment]
@julianoes I think that may be a typo.

**Comment by TSC21** [comment]
https://ignitionrobotics.org/api/math/0.1/classignition_1_1math_1_1Quaternion.html#a1ad9bd946d762ce60994979cec1bfd4e - `SetFromEuler()` has `RPY` order, so this is a typo. I find awkward that the estimators don't complain though.

**Comment by TSC21** [comment]
> I find awkward that the estimators don't complain though.

Well the reason is because none of the PX4 estimators fuses roll or pitch from vision, just yaw. So that's why it never complaint.

**Comment by TSC21** [comment]
Fixed in https://github.com/PX4/sitl_gazebo/pull/203/commits/33bb12596bf6ba729d057588d473eda28461cb76.
