### ISSUE TITLE
Bidirectional Motor

### ISSUE THREAD

**Issue by ganeshrk95** [PX4/PX4-SITL_gazebo-classic#197]
In my project, I have a bidirectional motor and it is controlled using the auxiliary port and an ESC configured to rotate bidirectionally. I know that the motor_model on sitl_gazebo either rotates in CW or CCW. Can anyone give some suggestions about I can go about changing this to make it bidirectional? (eg: -1 to 0 control input for reverse, 0 to 1 for forward). 
![image](https://user-images.githubusercontent.com/13117114/38117617-0428cc92-3384-11e8-9f24-e1055043f3bf.png)

The motor is placed on the tail arm of a tricopter.

@TSC21

**Comment by TSC21** [comment]
This is related to the mixer itself. Then, on the SDF file, you should create a "tilt" revolute joint and have a channel for the `mavlink_interface` that controls the motor using a position `joint_control_type`.
