### ISSUE TITLE
Gazebo 9 wind

### ISSUE THREAD

**Issue by danividanivi** [PX4/PX4-SITL_gazebo-classic#202]
I was using sit with Gazebo 7 without any problem.
Now I need to make use of wind functionality included in Gazebo 9.
Is it possible to do so? make posix_sitl_default gazebo throws a lot of errors with Gazebo 9 installed instead of Gazebo 7.

**Comment by TSC21** [comment]
@danividanivi did you set the build for the wind plugin (by uncommenting https://github.com/PX4/sitl_gazebo/blob/master/CMakeLists.txt#L252 and https://github.com/PX4/sitl_gazebo/blob/master/CMakeLists.txt#L284 or are you trying to use the Gazebo 9 [wind plugin](https://bitbucket.org/osrf/gazebo/src/5bb138770bfd97c53f1a34474b99d2b9fbd0e8f8/plugins/WindPlugin.cc?at=default&fileviewer=file-view-default)? Also you seem to mix two issues into one - you should now be able to build `sitl_gazebo` upstream master with Gazebo 9 compatibility. I am closing this for now, but let us know if you encounter issues when building the repo again.
