### ISSUE TITLE
cannot find mavlink_sitl_gazebo

### ISSUE THREAD

**Issue by FaboNo** [PX4/PX4-SITL_gazebo-classic#232]
I installed px firmware under ws/src/Firmware and `make posix_sitl_default gazebo`
in the catkin_ws I have also mavros installed without any issue
I ran catkin build on the root as well. But I have to mention that `catkin build` does not build anything under the firmware folder. I have to do build sitl_gazbo with cmake.

The problem I have is that when I take a look at `mavros_posix_sitl.launch `, the script is searching for (find mavlink_sitl_gazebo) and (find px4)  but unfortunately I cannot find mavlink_sitl_gazebo nor px4 (not in catkin_ws/build or usr:share/gazebo-7) - even  `find / -name "mavlink_sitl_gazebo" -type d ` does not find it.

so when I launch:
`roslaunch px4 mavros_posix_sitl.launch`
Gazebo is starting with an empty world and a Iris model but I do not know from where it is coming (it takes the file  catkin_ws/src/Firmware/Tools/sitl_gazebo/worlds/empty.world)

![sitl_gazebo](https://user-images.githubusercontent.com/31440972/45813190-38638380-bcd2-11e8-8f81-9eae67780cad.png)

Can someone can tell me what am I missing?
Thank you

**Comment by EliaTarasov** [comment]
Could you specify more accurate what problem do you have?
Seems like you did everything ok.
`mavlink_sitl_gazebo` and `px4` are packages, not executables. 
Generally you don't `catkin_make` or `catkin build` under `Firmware` directory.
ROS already has `gazebo_ros` executable node which is called everytime you run `mavlink_sitl_gazebo` or `px4` packages.

**Comment by TSC21** [comment]
This is no longer an issue: https://github.com/PX4/Firmware/pull/10587

**Comment by FaboNo** [comment]
Thank you Elia for your answer
Fabrice
