### ISSUE TITLE
Got stuck in "Performing build step for 'sitl_gazebo' "

### ISSUE THREAD

**Issue by Kumaron** [PX4/PX4-SITL_gazebo-classic#242]
I just downloaded `ubuntu_sim_ros_gazebo.sh` and finished the installation. 
I tried to do px4 sitl simulation by `make posix_sitl_default gazebo`, it got stuck in `Performing build step for 'sitl_gazebo'`. It took a very long time to get into gazebo. Is there any solution that can solve this? 
And when I tried it the second time, it just got stuck in `Performing build step for 'sitl_gazebo'` and cannot get into gazebo.

**Comment by Kumaron** [comment]
kumaron@ubuntu:~/src/Firmware$ make posix_sitl_default gazebo
ninja: Entering directory `/home/kumaron/src/Firmware/build/posix_sitl_default'
[2/6] Performing configure step for 'sitl_gazebo'
-- install-prefix: /usr/local
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   thread
--   timer
--   chrono
--   date_time
--   atomic
-- Boost version: 1.58.0
-- Building klt_feature_tracker without catkin
-- Building OpticalFlow with OpenCV
-- catkin DISABLED
Gazebo version: 7.14
-- Using C++17 compiler
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kumaron/src/Firmware/build/posix_sitl_default/build_gazebo
[3/6] Performing build step for 'sitl_gazebo'

Above is how it shows when I try to run `make posix_sitl_default gazebo`, and it just stops in `[3/6] Performing build step for 'sitl_gazebo'`.

**Comment by Kumaron** [comment]
kumaron@ubuntu:~/src/Firmware$ make posix_sitl_default gazebo
ninja: Entering directory `/home/kumaron/src/Firmware/build/posix_sitl_default'
[2/6] Performing configure step for 'sitl_gazebo'
-- install-prefix: /usr/local
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   thread
--   timer
--   chrono
--   date_time
--   atomic
-- Boost version: 1.58.0
-- Building klt_feature_tracker without catkin
-- Building OpticalFlow with OpenCV
-- catkin DISABLED
Gazebo version: 7.14
-- Using C++17 compiler
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kumaron/src/Firmware/build/posix_sitl_default/build_gazebo
[3/6] Performing build step for 'sitl_gazebo'
[1/2] Building CXX object CMakeFiles/gazebo_geotagged_images_plugin.dir/src/gazebo_geotagged_images_plugin.cpp.o
[2/2] Linking CXX shared library libgazebo_geotagged_images_plugin.so
[6/6] cd /home/kumaron/src/Firmware/bu.../src/Firmware/build/posix_sitl_default
SITL ARGS
sitl_bin: /home/kumaron/src/Firmware/build/posix_sitl_default/bin/px4
debugger: none
program: gazebo
model: none
src_path: /home/kumaron/src/Firmware
build_path: /home/kumaron/src/Firmware/build/posix_sitl_default
empty model, setting iris as default
GAZEBO_PLUGIN_PATH :/home/kumaron/src/Firmware/build/posix_sitl_default/build_gazebo
GAZEBO_MODEL_PATH :/home/kumaron/src/Firmware/Tools/sitl_gazebo/models
LD_LIBRARY_PATH /home/kumaron/catkin_ws/devel/lib:/opt/ros/kinetic/lib:/opt/ros/kinetic/lib/x86_64-linux-gnu:/home/kumaron/src/Firmware/build/posix_sitl_default/build_gazebo
SITL COMMAND: /home/kumaron/src/Firmware/build/posix_sitl_default/bin/px4 /home/kumaron/src/Firmware/ROMFS/px4fmu_common -s etc/init.d-posix/rcS -t /home/kumaron/src/Firmware/test_data
Gazebo multi-robot simulator, version 7.14.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

INFO  [Unknown] Creating symlink /home/kumaron/src/Firmware/ROMFS/px4fmu_common -> /home/kumaron/src/Firmware/build/posix_sitl_default/tmp/rootfs/etc
99 WARNING: setRealtimeSched failed (not run as root?)

______  __   __    ___ 
| ___ \ \ \ / /   /   |
| |_/ /  \ V /   / /| |
|  __/   /   \  / /_| |
| |     / /^\ \ \___  |
\_|     \/   \/     |_/

px4 starting.

INFO  [Unknown] Calling startup script: /bin/sh etc/init.d-posix/rcS 0
[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 192.168.8.116
Gazebo multi-robot simulator, version 7.14.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 192.168.8.116
INFO  [dataman] Unknown restart, data manager file './dataman' size is 11405132 bytes
INFO  [simulator] Waiting for initial data on UDP port 14560. Please start the flight simulator to proceed..
libGL error: failed to create drawable
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  26 (X_GLXMakeContextCurrent)
  Serial number of failed request:  33
  Current serial number in output stream:  33
[Dbg] [gazebo_mavlink_interface.cpp:138] <joint_name> not found for channel[0] no joint control will be performed for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:138] <joint_name> not found for channel[1] no joint control will be performed for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:138] <joint_name> not found for channel[2] no joint control will be performed for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:138] <joint_name> not found for channel[3] no joint control will be performed for this channel.
[Wrn] [gazebo_mavlink_interface.cpp:127] joint [zephyr_delta_wing::propeller_joint] not found for channel[4] no joint control for this channel.
[Wrn] [gazebo_mavlink_interface.cpp:127] joint [zephyr_delta_wing::flap_left_joint] not found for channel[5] no joint control for this channel.
[Wrn] [gazebo_mavlink_interface.cpp:127] joint [zephyr_delta_wing::flap_right_joint] not found for channel[6] no joint control for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:138] <joint_name> not found for channel[7] no joint control will be performed for this channel.
[Msg] Using MAVLink protocol v2.0
[Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/default/iris/motors, deleting message. This warning is printed only once.
INFO  [simulator] Got initial simulation data, running sim..
INFO  [init] Mixer: etc/mixers/quad_w.main.mix on /dev/pwm_output0
INFO  [mavlink] mode: Normal, data rate: 4000000 B/s on udp port 14570 remote port 14550
INFO  [mavlink] mode: Onboard, data rate: 4000000 B/s on udp port 14580 remote port 14540
INFO  [logger] logger started (mode=all)
INFO  [mavlink] MAVLink only on localhost (set param MAV_BROADCAST = 1 to enable network)
INFO  [Unknown] Startup script returned successfully
pxh> INFO  [logger] Start file log (type: full)
INFO  [logger] Opened full log file: ./log/2018-10-31/02_16_27.ulg
INFO  [ecl/EKF] EKF aligned, (pressure height, IMU buf: 22, OBS buf: 14)
INFO  [ecl/EKF] EKF GPS checks passed (WGS-84 origin set)
INFO  [ecl/EKF] EKF commencing GPS fusion
[Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/default/iris/imu, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/default/iris/motor_speed/0, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/default/iris/motor_speed/1, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/default/iris/motor_speed/2, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/default/iris/motor_speed/3, deleting message. This warning is printed only once.

I tried again, it shows above messages and just won't get into gazebo.

How can I solve this problem? Thanks in advance!

**Comment by Kumaron** [comment]
Emmmm it works at last, maybe because it was loading resources and my ubuntu PC is too old?

**Comment by LorenzMeier** [comment]
I'm closing this for now. Also `make distclean` can help to clean up your installed state.
