### ISSUE TITLE
tinyxml2 dependency problem

### ISSUE THREAD

**Issue by julianoes** [PX4/PX4-SITL_gazebo-classic#247]
I'm getting the following build error on Arch Linux with latest master (2adc86b5bf84543091470966caf33c3b4f3ee666).

```
[ 41%] Linking CXX static library libklt_feature_tracker.a
gz: error while loading shared libraries: libtinyxml2.so.6: cannot open shared object file: No such file or directory
make[7]: *** [CMakeFiles/sdf.dir/build.make:65: /home/julianoes/src/Firmware-master/Tools/sitl_gazebo/models/iris/iris.sdf] Error 127
make[7]: *** Deleting file '/home/julianoes/src/Firmware-master/Tools/sitl_gazebo/models/iris/iris.sdf'

```

**Comment by TSC21** [comment]
@julianoes did you confirm that you have libtinyxml2 on your Arch dist?
We probably need to set a new parallel build for arch in CI to make sure we have building on the most common OS's.

**Comment by julianoes** [comment]
I have `tinyxml2`, and I can see that the linking error is somehow from `gz`, so that's confusing.

**Comment by TSC21** [comment]
So, out of our hands? Maybe something to report on the Gazebo bitbucket repo?

**Comment by julianoes** [comment]
Ok I get it. Gazebo tries to access the wrong lib version.
```
ls -l /usr/lib | grep tinyxml2
lrwxrwxrwx 1 root root        16 Nov 18 17:46 libtinyxml2.so -> libtinyxml2.so.7
lrwxrwxrwx 1 root root        20 Nov 18 17:46 libtinyxml2.so.7 -> libtinyxml2.so.7.0.1
-rwxr-xr-x 1 root root    100312 Nov 18 17:46 libtinyxml2.so.7.0.1
```

Thanks @TSC21.

**Comment by TSC21** [comment]
Np. Glad you figured it out!

**Comment by julianoes** [comment]
To follow up with this: even though I recompiled gazebo after the tinyxml2 update, it still had reference to the old library. Actually needed was a recompilation of `ignition-common`.
