### ISSUE TITLE
RTSP stream from gazebo camera created by DCM constantly shows initial frame

### ISSUE THREAD

**Issue by b4cedev** [PX4/PX4-SITL_gazebo-classic#253]
Hi!
I successfully built & ran PX4, Gazebo & Dronecode camera manager with a v4l2 camera, but I have trouble getting a continuous video stream from the Gazebo camera...
When accessing the gazebo camera RTSP stream, vlc receives the same initial frame over and over (vlc media info indicates constantly flowing data), so it seems dcm fails to receive further camera images from Gazebo.
I also enabled libgazebo_gst_camera_plugin and let qgc show this stream which works without issues and reflects drone movements near realtime.
Currently PX4 1.8.2, Gazebo 9 & DCM master run on an Ubuntu 18.04 host, all dependencies are installed from the original Ubuntu repositories, no PPAs or such. 
As told in the dcm docs I first raised this issue on slack in #camera-payload-api channel, where I was instructed to post it here.
Does anybody have clue what's going on here?

**Comment by LorenzMeier** [comment]
Thanks for reporting. I will have a quick look.
