### ISSUE TITLE
Error while using matrice 100 model 

### ISSUE THREAD

**Issue by samarth8927** [PX4/PX4-SITL_gazebo-classic#254]
While adding model to gazebo for Matrice -100 I got the following error:
Error [parser.cc:286] Error finding file [/home/sam_ros/src/sitl_gazebo/models/matrice_100/matrice_100-gen.sdf].

**Comment by TSC21** [comment]
@samarth8927 what procedures did you follow to "add" the model? The Matrice 100 model is generated on build time using a jinja generator Python script. Did you build the repository?

**Comment by samarth8927** [comment]
I am utilizing the insert tab of gazebo. I think the issue is with .sdf.jinja files as I am able to insert .sdf based models. I am actually new to gazebo, I did build sitl_gazebo repository. Can you please tell how to use a jinja generator python script, as i am unable to find much information with this regard on internet.

**Comment by TSC21** [comment]
When you build `sitl_gazebo`, on the build process, you get an output like this:
```sh
/home/nuno/PX4/Firmware/Tools/sitl_gazebo/models/3DR_gps_mag/3DR_gps_mag.sdf.jinja -> /home/nuno/PX4/Firmware/Tools/sitl_gazebo/models/3DR_gps_mag/3DR_gps_mag-gen.sdf
/home/nuno/PX4/Firmware/Tools/sitl_gazebo/models/c920/c920.sdf.jinja -> /home/nuno/PX4/Firmware/Tools/sitl_gazebo/models/c920/c920-gen.sdf
/home/nuno/PX4/Firmware/Tools/sitl_gazebo/models/mb1240-xl-ez4/mb1240-xl-ez4.sdf.jinja -> /home/nuno/PX4/Firmware/Tools/sitl_gazebo/models/mb1240-xl-ez4/mb1240-xl-ez4-gen.sdf
/home/nuno/PX4/Firmware/Tools/sitl_gazebo/models/pixhawk/pixhawk.sdf.jinja -> /home/nuno/PX4/Firmware/Tools/sitl_gazebo/models/pixhawk/pixhawk-gen.sdf
/home/nuno/PX4/Firmware/Tools/sitl_gazebo/models/matrice_100/matrice_100.sdf.jinja -> /home/nuno/PX4/Firmware/Tools/sitl_gazebo/models/matrice_100/matrice_100-gen.sdf
/home/nuno/PX4/Firmware/Tools/sitl_gazebo/models/px4flow/px4flow.sdf.jinja -> /home/nuno/PX4/Firmware/Tools/sitl_gazebo/models/px4flow/px4flow-gen.sdf
/home/nuno/PX4/Firmware/Tools/sitl_gazebo/models/r200/r200.sdf.jinja -> /home/nuno/PX4/Firmware/Tools/sitl_gazebo/models/r200/r200-gen.sdf
/home/nuno/PX4/Firmware/Tools/sitl_gazebo/models/sf10a/sf10a.sdf.jinja -> /home/nuno/PX4/Firmware/Tools/sitl_gazebo/models/sf10a/sf10a-gen.sdf
```
So, the module you should add is `matrice_100-gen.sdf`, which is autogenerated on build time and put under `sitl_gazebo/models/matrice_100/`.
