### ISSUE TITLE
Error during build of SITL_gazebo

### ISSUE THREAD

**Issue by samarth8927** [PX4/PX4-SITL_gazebo-classic#255]
While building i am getting the following error:
[  0%] Building CXX object CMakeFiles/gazebo_geotagged_images_plugin.dir/src/gazebo_geotagged_images_plugin.cpp.o
/home/sam_ros/src/sitl_gazebo/src/gazebo_geotagged_images_plugin.cpp: In member function ‘void gazebo::GeotaggedImagesPlugin::_handle_request_camera_settings(const mavlink_message_t*, sockaddr*)’:
/home/sam_ros/src/sitl_gazebo/src/gazebo_geotagged_images_plugin.cpp:563:12: error: too many arguments to function ‘uint16_t mavlink_msg_camera_settings_pack_chan(uint8_t, uint8_t, uint8_t, mavlink_message_t*, uint32_t, uint8_t)’
         NAN);                   // Focus level
            ^
In file included from /home/sam_ros/catkin_ws/devel/include/mavlink/v2.0/common/common.h:1426:0,
                 from /home/sam_ros/catkin_ws/devel/include/mavlink/v2.0/common/mavlink.h:32,
                 from /home/sam_ros/src/sitl_gazebo/include/gazebo_geotagged_images_plugin.h:20,
                 from /home/sam_ros/src/sitl_gazebo/src/gazebo_geotagged_images_plugin.cpp:18:
/home/sam_ros/catkin_ws/devel/include/mavlink/v2.0/common/./mavlink_msg_camera_settings.h:82:24: note: declared here
 static inline uint16_t mavlink_msg_camera_settings_pack_chan(uint8_t system_id,
                        ^
CMakeFiles/gazebo_geotagged_images_plugin.dir/build.make:62: recipe for target 'CMakeFiles/gazebo_geotagged_images_plugin.dir/src/gazebo_geotagged_images_plugin.cpp.o' failed
make[2]: *** [CMakeFiles/gazebo_geotagged_images_plugin.dir/src/gazebo_geotagged_images_plugin.cpp.o] Error 1
CMakeFiles/Makefile2:112: recipe for target 'CMakeFiles/gazebo_geotagged_images_plugin.dir/all' failed
make[1]: *** [CMakeFiles/gazebo_geotagged_images_plugin.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by TSC21** [comment]
https://github.com/PX4/sitl_gazebo/pull/250#issuecomment-441066686
