### ISSUE TITLE
GPS plugin - groundtruth message - altitude calculation is wrong

### ISSUE THREAD

**Issue by jros92** [PX4/PX4-SITL_gazebo-classic#259]
In line 209 of gazebo_gps_plugin.cpp, for computation of the groundtruth message, the gazebo world position Z-value gets subtracted, when it should be added to the home altitude just like it is done for the GPS message.

https://github.com/PX4/sitl_gazebo/blob/c90e8ad2b27b95dc0b4c45b346509477c5fa593d/src/gazebo_gps_plugin.cpp#L209

Line 209 should be: `groundtruth_msg.set_altitude(pos_W_I.Z() + alt_home);`

**Comment by TSC21** [comment]
Yep that's a big. Thanks for the catch. Can you issue a PR to fix it? Thanks!
