### ISSUE TITLE
[Question] plane: remove camera?

### ISSUE THREAD

**Issue by lamping7** [PX4/PX4-SITL_gazebo-classic#269]
Should we split the current plane model into two? One with a camera and one without. This may help narrow CI testing issues. @julianoes @TSC21 @dagar @LorenzMeier 

Added here https://github.com/PX4/sitl_gazebo/commit/d45bfd13ac83ad7f87c658d7827577ce60a051fb

**Comment by julianoes** [comment]
We might as well. I've never seen it in action.

**Comment by TSC21** [comment]
I am ok with this.

**Comment by tfoote** [comment]
I'm about to deploy with it for a project, but can adapt to a new model as long as it's split and not removed. It does make sense to have a simpler version available.
