### ISSUE TITLE
Question about magnetic field data

### ISSUE THREAD

**Issue by EliaTarasov** [PX4/PX4-SITL_gazebo-classic#278]
[Magnetic filed data](https://github.com/PX4/sitl_gazebo/blob/master/src/gazebo_mavlink_interface.cpp#L283) provided for Zurich states that D-component has negative sign. However [WMM2015 Online Calculator](https://www.ngdc.noaa.gov/geomag/calculators/magcalc.shtml#igrfwmm) provides positive sign. Reverse of this sign seem has no affect on flight performance but anyway it's good to fix it if it's wrong. What's the reason for this?

**Comment by julianoes** [comment]
Do you know the coordinate frames of the source and the field needed in sitl_gazebo?

**Comment by EliaTarasov** [comment]
According to [this](https://github.com/PX4/sitl_gazebo/blob/master/src/gazebo_mavlink_interface.cpp#L599) and to [this](https://github.com/PX4/sitl_gazebo/blob/master/src/gazebo_mavlink_interface.cpp#L624) the only rotations applied are declination and successive rotation to body. So seems like the source `mag_d_` frame must be the NED.

**Comment by CarlOlsson** [comment]
Why not get the strength and inclination also from the [geo lookup tables](https://github.com/PX4/ecl/blob/master/geo_lookup/geo_mag_declination.cpp)?

**Comment by EliaTarasov** [comment]
@CarlOlsson That's much better solution. I'll add this then.
Upd: Not sure. The question: what is the best way to include mag tables into `sitl_gazebo`? 
I see two options: include `ecl` code or copy mag tables as a separate code into `sitl_gazebo`.

**Comment by julianoes** [comment]
I'd say copy it in.

**Comment by EliaTarasov** [comment]
Done.

**Comment by EliaTarasov** [comment]
Closed by [PR](https://github.com/PX4/sitl_gazebo/pull/282)
