### ISSUE TITLE
Populate gps.s_variance_m_s in sitl

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/PX4-SITL_gazebo-classic#285]
Currently SITL publishes `gps.s_variance_m_s = 0` which is bad since it is used in several places inside EKF2. A constant value of around 0.25 would be much better

**Comment by TSC21** [comment]
@CarlOlsson this has nothing to do with `sitl_gazebo` as far as I know. Simulated GPS data coming from Gazebo do have EPH and EPV associated.
