### ISSUE TITLE
Gazebo SITL and PX4 not handling simulated wind correctly for fixed wing

### ISSUE THREAD

**Issue by Antiheavy** [PX4/PX4-SITL_gazebo-classic#287]
moving https://github.com/PX4/Firmware/issues/11319 to the appropriate repo.

based on a conversation with @TSC21 I suspect recent changes to the wind model are not properly accounting for fixed wing airspeed measurement and therefore wind estimation.

As pointed out by @CHschizo in this other issue post here: [#11116 (comment)](https://github.com/PX4/Firmware/issues/11116#issuecomment-452724619) the wind estimate and flight performance isn't working correctly in Gazebo SITL. See screenshot below of the vehicle tracking offset to the intended location east-west cross-track error, but tracking okay north-south cross-track error.

This screenshot is using the default PX4 Gazebo Plane model:
![image](https://user-images.githubusercontent.com/12117027/53306572-5cfcf200-3854-11e9-93fe-a1698e0b29ff.png)

**Comment by Antiheavy** [comment]
@TSC21 should we just disable the wind module for fixed wing?  or can this be fixed easily?

**Comment by Jaeyoung-Lim** [comment]
@Antiheavy Are there any updates on this?

**Comment by xdwgood** [comment]
@Antiheavy  I also encountered this problem, how can I set the simulation to wind = 0? thanks

**Comment by Antiheavy** [comment]
@Jaeyoung-Lim @xdwgood I just made a PR that shows how I worked around this.  I don't know if this PR will be accepted, but it worked for me.
https://github.com/PX4/sitl_gazebo/pull/364

**Comment by Antiheavy** [comment]
It looks like @Jaeyoung-Lim is working on a true fix to this problem in this PR: https://github.com/PX4/sitl_gazebo/pull/375

**Comment by nikmad** [comment]
What is the difference between wind in 'windDirection' and wind gust in this plugin? Are these both parameters referring to 'wind gust' that comes erratically on top of normal relative wind as seen from the aircraft by virtue of its relative velocity?
      <windDirection>0 1 0</windDirection>
      <windGustDirection>0 0 0</windGustDirection>

**Comment by nikmad** [comment]
What is the difference between **wind** in 'windDirection' and **wind gust** in this plugin? Are these both parameters referring to 'wind gust' that comes erratically on top of normal relative wind as seen from the aircraft by virtue of its relative velocity?
>  <windDirection>0 1 0</windDirection>
> <windGustDirection>0 0 0</windGustDirection>

**Comment by nikmad** [comment]
What is the difference between wind in 'windDirection' and wind gust in 'windGustDirection' in this plugin? Are these both parameters referring to 'wind gust' that comes erratically on top of normal relative wind as seen from the aircraft by virtue of its relative velocity?

**Comment by LorenzMeier** [comment]
@Jaeyoung-Lim Got this fixed in the interim?

**Comment by Jaeyoung-Lim** [comment]
@LorenzMeier Yes, this should have been fixed with https://github.com/PX4/sitl_gazebo/pull/375
