### ISSUE TITLE
Abort on startup because port is occupied

### ISSUE THREAD

**Issue by julianoes** [PX4/PX4-SITL_gazebo-classic#289]
Since the introduction of lockstep (#257) we see an abort on startup quite often:

```
(1551081994 550255675) [Err] [gazebo_mavlink_interface.cpp:416] bind failed: Address already in use, aborting
```

The problem is that we can't bind to the port if it is already in use. However, it should not happen in the first place that the port is already in use (unless Gazebo SITL is already running).
My guess is that we either don't close the port properly, or we don't shutdown gzserver correctly and therefore the port does not get cleaned up properly.

Initially reported by @mrivi.

**Comment by shrit** [comment]
I am having this problem most of the time, in most cases it is due to the fact that gazebo server is still running. I need to kill it manually to be able close the used ports

**Comment by julianoes** [comment]
> I need to kill it manually to be able close the used ports

If it's still running, there is not much we can do. The PX4 SITL scripts usually clean up when you do Ctrl+C or type `shutdown`. And in this case it should all get cleaned up now.
