### ISSUE TITLE
World rubble not working

### ISSUE THREAD

**Issue by julianoes** [PX4/PX4-SITL_gazebo-classic#290]
According to @mrivi the world rubble is not working:

> I noticed that the world `rubble` is not working. @TSC21 do you know where it's used?

@mrivi how can you reproduce "not working", how do you choose rubble?

**Comment by mrivi** [comment]
I launch it from ros where `world_path` is the path to `rubble.world`

```bash
<include file="$(find gazebo_ros)/launch/empty_world.launch">
        <arg name="world_name" value="$(arg world_path)" />
    </include>
```

First I noticed that the `real_time_update_rate` was not set properly to work with the lockstep (same issue we had with the avoidance. it's 1000 instead of 250). But even fixing that, the world never loads into gazebo.

**Comment by julianoes** [comment]
What about the other params, not just `real_time_update_rate` but also the `max_step_size`?

And where is this file?

**Comment by mrivi** [comment]
I was wrong. I can load it 
![rubble](https://user-images.githubusercontent.com/15078736/53346573-93e80c00-3917-11e9-9a2e-33cf821f01c1.png)

but 
```bash
WARN  [ecl/EKF] EKF baro hgt timeout - reset to baro
WARN  [ecl/EKF] EKF baro hgt timeout - reset to baro
WARN  [ecl/EKF] EKF baro hgt timeout - reset to baro
WARN  [ecl/EKF] EKF GPS fusion timeout - reset to GPS
WARN  [ecl/EKF] EKF baro hgt timeout - reset to baro
WARN  [ecl/EKF] EKF baro hgt timeout - reset to baro
WARN  [ecl/EKF] EKF baro hgt timeout - reset to baro
WARN  [ecl/EKF] EKF baro hgt timeout - reset to baro
WARN  [ecl/EKF] EKF baro hgt timeout - reset to baro
WARN  [ecl/EKF] EKF baro hgt timeout - reset to baro
WARN  [ecl/EKF] EKF GPS fusion timeout - reset to GPS
WARN  [ecl/EKF] EKF GPS fusion timeout - reset to GPS
WARN  [ecl/EKF] EKF baro hgt timeout - reset to baro
WARN  [ecl/EKF] EKF baro hgt timeout - reset to baro
WARN  [ecl/EKF] EKF baro hgt timeout - reset to baro
WARN  [ecl/EKF] EKF baro hgt timeout - reset to baro
WARN  [ecl/EKF] EKF baro hgt timeout - reset to baro
WARN  [ecl/EKF] EKF baro hgt timeout - reset to baro
WARN  [ecl/EKF] EKF baro hgt timeout - reset to baro
WARN  [ecl/EKF] EKF GPS fusion timeout - reset to GPS
WARN  [commander] Arming DENIED. Manual throttle non-zero.
WARN  [ecl/EKF] EKF GPS fusion timeout - reset to GPS
WARN  [commander] Preflight Fail: Position unknown
WARN  [commander] Preflight Fail: Accel Range, hold still on arming
WARN  [commander] Preflight Fail: Accel Range, hold still on arming
```

You can launch it `roslaunch px4 posix_sitl.launch world:=$(find mavlink_sitl_gazebo)/worlds/rubble.world`

**Comment by TSC21** [comment]
@mrivi is this still an issue?

**Comment by RicardoM17** [comment]
I assume that now this is no longer an issue considering it was removed in #453

@julianoes this can probably be closed.
