### ISSUE TITLE
has no member named 'velocity_covariance'

### ISSUE THREAD

**Issue by jungmineeee** [PX4/PX4-SITL_gazebo-classic#291]
I followed the commands. also, append the 'exports ' path in the ~/.bashrc file

![image](https://user-images.githubusercontent.com/39642305/53359562-99c10a00-3976-11e9-930d-2886da7e5d39.png)
(I'm using the newest VirtualBox and Ubuntu 16.04 LTS version, I set the VirtualBox for sharing the clipboard but it doesn't work. So I put these pictures)

When I do the command "make", there's an error raised. 

![image](https://user-images.githubusercontent.com/39642305/53359807-52874900-3977-11e9-96e3-fb66aad9fec6.png)

I'm new for this field(robotics or something similar). So, I don't know well about this kind of thing. 
can you help me to fix this problem? I really need some help. ;(

**Comment by Kchour** [comment]
I have the exact error as well

**Comment by mhkabir** [comment]
@TSC21

**Comment by Kchour** [comment]
So I solved my issue by including the following repo files (https://github.com/mavlink/c_library_v2) into **/usr/local/mavlink/v2.0/**

Make sure you extract all the files like so...

![image](https://user-images.githubusercontent.com/21199708/53373805-238fb980-391c-11e9-90f1-3907776f222d.png)

**Comment by TSC21** [comment]
This only occurs when `sitl_gazebo` CMake fetches the Mavlink headers from the `ros-..-mavlink` install. When it's not updated, results on the above error. So or you take @Kchour solution or you need to wait for the `mavlink-gbp-release` to come out on the ROS build farm and then released as a deb package.
