### ISSUE TITLE
How to change the local_position stream rate?

### ISSUE THREAD

**Issue by Seanmatthews** [PX4/PX4-SITL_gazebo-classic#293]
I'm running simulation using PX4+MAVROS+Gazebo and I can't seem to find the way for increasing the rate of the `/mavros/local_position/pose` measurement that MAVROS returns (and hence, the transform that's published between `base_link` and its parent). I'm looking for whatever parameter is akin to setting `mavlink stream -r 200 LOCAL_POSITION_NED ...` in a px4 config file.

**Comment by TSC21** [comment]
The streams are changes on PX4. Not in sitl_gazebo or MAVROS. The stream as you are looking to change has to be added in a config file or manually set on a nsh shell.
