### ISSUE TITLE
Tiltrotor simulation when vehicle is disarmed 

### ISSUE THREAD

**Issue by isidroas** [PX4/PX4-SITL_gazebo-classic#296]
I've done the simulation of a tiltrotor and I've seen a strange behavorial. When the vehicle is disarmed, its rotors are waving. 
![Alt Text](https://media.giphy.com/media/YAXPpaR0T8PRfG22xW/giphy.gif)

When I run 
pxh> listener actuator_outputs
I get this:
~~~~
   TOPIC: actuator_outputs instance 0 #1
    actuator_outputs_s
	   timestamp: 223652000  (0.000000 seconds ago)
	   noutputs: 11
	   output: [900.0000, 900.0000, 900.0000, 900.0000, 900.0000, 900.0000, 900.0000, 900.0000, 
   900.0000, 900.0000, 900.0000, nan, nan, nan, nan, nan]
~~~~

Is this this behavorial desired?

**Comment by dagar** [comment]
No, that's not desired. I think this explains some of the intermittent failures we see in the PX4 CI system.

**Comment by dlwalter** [comment]
I am seeing this too.  Servos are violently shaking on the Tiltrotor model in gazebo.  Is there any fix for this?

**Comment by isidroas** [comment]
I achieved to solve that problem by changing the PID parameters of the motors. The first one is this [line](https://github.com/PX4/sitl_gazebo/blob/95adbb11f8deef06fb132bf0eb85c19e6ca00f6e/models/tiltrotor/tiltrotor.sdf#L1107)

**Comment by Jaeyoung-Lim** [comment]
This has been fixed by https://github.com/PX4/sitl_gazebo/pull/386

@isidroas @dlwalter  Could you give it a try please?
