### ISSUE TITLE
Why is the local position pose of simulated UAVs at -90 degrees to their heading?

### ISSUE THREAD

**Issue by jannsta1** [PX4/PX4-SITL_gazebo-classic#303]
I'm using the sitl_gazebo library with ROS (making use of the MAVROS package). It seems like the topics describing the orientation of the UAV with this setup (e.g. /mavros/local_position/pose) are rotated -90 degrees w.r.t. the front of the drone - I wonder if this is indeed how it is supposed to be configured? 

This means if I send a velocity setpoint in the X direction with the setpoint raw message with the coordinate_frame set to FRAME_BODY_NED(8) the UAV straffes sideways (which seems counter intuitive to me at the moment).

**Comment by TSC21** [comment]
ROS: ENU orientation; FMU: NED orientation.
