### ISSUE TITLE
How to use wind plugin?

### ISSUE THREAD

**Issue by slowmathematician** [PX4/PX4-SITL_gazebo-classic#320]
Gazebo upstream have [wind plugin](https://bitbucket.org/osrf/gazebo/src/5bb138770bfd97c53f1a34474b99d2b9fbd0e8f8/plugins/WindPlugin.cc?at=default&fileviewer=file-view-default) and sitl_gazebo have [own wind plugin](https://github.com/PX4/sitl_gazebo/blob/master/src/gazebo_wind_plugin.cpp).
What is the difference ?
What units of [wind linear velocity](http://sdformat.org/spec?ver=1.6&elem=world#world_wind) (meters per second or force in newtons) ?
How to load the sitl wind plugin ?

**Comment by Jaeyoung-Lim** [comment]
@slowmathematician As for today, the wind is modeled as a force (therefore newtons). Hopefully this PR https://github.com/PX4/sitl_gazebo/pull/375 changes it to m/s
