### ISSUE TITLE
Help understanding gazebo plugins in SITL

### ISSUE THREAD

**Issue by tuloski** [PX4/PX4-SITL_gazebo-classic#331]
I'm having troubles understanding how gazebo plugins are integrated in the SITL software.
Appartently the plugin (for example the GPS plugin) retrieves all the data from gazebo "api" and it should publish some topics (/gps and /groundtruth in GPS plugin).
But actually I can't see any topic published. Only the manipulated data from MAVROS plugins.

So how is the whole chain of data working?
Is there any documentation I didn't see?

**Comment by tuloski** [comment]
Oh, I see that the plugins publish topics on gazebo topics and not ros topics.
Then who is reading the gazebo topics?

**Comment by TSC21** [comment]
`sitl_gazebp` has plugins that are compiled to be used within Gazebo. The topics published are used by other plugins. So plugin interact with plugins and with the simulation physics, and can exchange information using topics on the Gazebo Transport layer.
