### ISSUE TITLE
Help regarding dualrotor tailsitter

### ISSUE THREAD

**Issue by akshitj1** [PX4/PX4-SITL_gazebo-classic#333]
Hi, I am trying to find simulation files for dual rotor tailsitter as described in [Design and Implementation of an Unmanned Tail-sitter](http://people.inf.ethz.ch/pomarc/pubs/BapstIROS15.pdf) by  @RomanBapst et. al. . From what I can find, in tailsitter/tailsitter.sdf there are 4 rotors.

**Comment by xdwgood** [comment]
Hello @akshitj1  
Do you find dual rotor simulation files? 
I see this: https://github.com/akshitj1/sitl_gazebo  :+1: 
I try `make px4_sitl gazebo_hummingbird_fixed`....But the compilation failed, I will be grateful if you have your reply. :smiley:

**Comment by akshitj1** [comment]
Check [`original repo`](https://github.com/utiasSTARS/hummingbird_ws). These guys are trying to create opensource platform for tailsitter research. The controller is very naive but will serve as good starting point for simulation files. It seems to be a big overhead if someone just wants to simulate tailsitter (for eg. [`rotors_simulator`](https://github.com/ethz-asl/rotors_simulator)

**Comment by xdwgood** [comment]
@akshitj1  thank you :smiley: 
I will look at this： https://github.com/utiasSTARS/hummingbird_ws   :+1:

**Comment by Jaeyoung-Lim** [comment]
@xdwgood The link doesn't exist anymore...Do you have any pointers? I would be interested in getting the control surfaces of the duo tailsitter working in this repo

**Comment by xdwgood** [comment]
@Jaeyoung-Lim  I can upload my local reservation, but to be honest I did not run it successfully, hope you can get good results.

here:  https://github.com/xdwgood/Firmware/tree/jw_fix_all

Someone from my team seems to have done the job, but I heard that only five seconds can be flown, and the flight in gazebo will crash after five seconds.

**Comment by akshitj1** [comment]
@Jaeyoung-Lim , I see you are from ETH zurich. There was a paper on tailsitter control by Robin Ritz from your college. links: 
[`A global controller for flying wing tailsitter vehicles`](https://www.flyingmachinearena.ethz.ch/wp-content/uploads/ritzIEEE17.pdf)
[`Additional material in Robin's thesis in Appendix 5`](https://pdfs.semanticscholar.org/0668/3817ccd1aca8437e40443fe6c3fd199931c1.pdf)

**Comment by Jaeyoung-Lim** [comment]
@akshitj1 The problem with the current sitl_gazebo is not that we don't understand the dynamics, but the how to model the prop wash for the lift drag plugin. The current implementation thinks the control surfaces should stall during hover

**Comment by akshitj1** [comment]
@Jaeyoung-Lim , Regarding broken link, I think repo has been updated/renamed to: [PhoenixDrone-sitl_gazebo](https://github.com/utiasSTARS/PhoenixDrone-sitl_gazebo) . I haven't seen into the code but let me know if it helps. I am not sure if they have implemented the forward flight too as can be seen only to hover in [video](https://www.youtube.com/watch?v=vxNCJzuAJGc)

**Comment by Jaeyoung-Lim** [comment]
@akshitj1 I looked into the code and the repo you have forwarded only models the dynamics during hover, therefore a transition will not be possible

**Comment by xdwgood** [comment]
@Jaeyoung-Lim   Do you continue it? Thank you

**Comment by Jaeyoung-Lim** [comment]
@xdwgood Currently not working on it

**Comment by mengchaoheng** [comment]
@xdwgood [PR](https://github.com/PX4/PX4-SITL_gazebo-classic/pull/1083) is in progress.
