### ISSUE TITLE
How to make IRIS more powerful.

### ISSUE THREAD

**Issue by tuloski** [PX4/PX4-SITL_gazebo-classic#335]
Hi, I'd like to make the IRIS model more powerful, because now I reach thrust saturation when going at around 10m/s.
Is the process simple or do I need to touch the rotor_description?

**Comment by RicardoM17** [comment]
@tuloski not sure if you still have this issue but you can change the parameters on the iris.sdf to "solve" this.

Either increase the thrust coefficient or the max speed.

**Comment by tuloski** [comment]
Thanks. Yeah I increased both and it worked. I don't know if there is a limit or some stability issues.

**Comment by RicardoM17** [comment]
There are some issues if you increase them too much. You can also decrease the weight somewhat but all of these are just adaptations and not really the ideal solution.

Still this can be closed I believe @TSC21 .
