### ISSUE TITLE
rviz cannot load meshes from sitl_gazebo/models/rotors_description

### ISSUE THREAD

**Issue by saifullah3396** [PX4/PX4-SITL_gazebo-classic#345]
Hi, I am trying to visualize the urdf model of iris in RVIZ that is present in sitl_gazebo/models/rotors_description/urdf/iris.xacro. There is one problem though that in iris.xacro file, the argument 'rotors_description_dir' is used to locate the given directory in sitl_gazebo but file multirotor_base.xacro uses package// tag for finding 'rotors_description'. This causes multirotor_base.xacro to find the meshes in 'rotors_description' package installed in /opt/ros/<distro> instead of looking for it in sitl_gazebo/models/rotors_description/models. Though I am not entirely sure if this is the write way to go about it but I solved the problem by doing the following:
`Replace package://rotors_description with file://$(arg rotors_description_dir) in sitl_gazebo/models/rotors_description/urdf/multirotor_base.xacro`.

**Comment by Jaeyoung-Lim** [comment]
@saifullah3396 It looks like your `GAZEBO_MODEL_PATH` was not properly set. To see how to properly set the path you can
```
cd ~/src/Firmware
source Tools/setup_gazebo.bash $(pwd) $(pwd)/build/px4_sitl_default
```
