### ISSUE TITLE
"Already tracking action "&File" under id 56"--About px4_sitl debugging with gdb.

### ISSUE THREAD

**Issue by pxfdale** [PX4/PX4-SITL_gazebo-classic#347]
Hi, masters of UAV! Help!
I followed the tutorial [https://dev.px4.io/master/en/debug/simulation_debugging.html#start-combinations](url).
However, when I run `make px4_sitl_default gazebo_tailsitter_gdb`, the problem are as follows:
![image](https://user-images.githubusercontent.com/38657922/65493215-fd97bb00-dee4-11e9-938f-83fdb045d09c.png)
![image](https://user-images.githubusercontent.com/38657922/65493329-3cc60c00-dee5-11e9-8aa1-8238575a926f.png)

Does anyone know the reason? Wish to get help from you.

**Comment by julianoes** [comment]
I have never seen this before, no idea.
Can you just type `run` and hit enter or does it not work at all?

**Comment by LorenzMeier** [comment]
Closing as stale, no reply.
