### ISSUE TITLE
Gazebo gets stuck on spawning vehicle without px4 and crashes on respawn.

### ISSUE THREAD

**Issue by saifullah3396** [PX4/PX4-SITL_gazebo-classic#359]
On launching gazebo and spawning a vehicle (I have only tested with iris but it should exist in every robot), I saw the following bugs:
1) The gazebo gets stuck until px4 is launched. This should not happen ideally so that px4 can be opened and closed whenever we want and it should not conflict with gazebo.
2) On deleting the robot and respawning by following the same steps, gazebo crashes! This does not allow resetting gazebo world without having to restart the whole simulator every time.

I have checked why its happening and found a solution. On spawning a vehicle it launches the  
gazebo_mavlink_interface plugin which has a blocking socket and waits at the accept() function call for px4 connection to be made. The bug (1) can simple be solved by making the socket non-blocking but then we would also need to constantly check for a new connection by adding the accept() call in the update loop of the plugin for whenever a new connection is requested by px4. Can be done by simply by the following call for linux (not too sure about windows or other platforms):
```
fcntl(simulator_socket_fd_, F_SETFL, O_NONBLOCK);
```
Bug (2) happens because even if the socket is closed when we delete the vehicle, it remains opened in the background for some time. I solved the problem by making both the address and port reusable on the socket. Just adding following socket option did the trick:
```
int reuse = 1;
result = setsockopt(simulator_socket_fd_, SOL_SOCKET, SO_REUSEADDR, &reuse, sizeof(reuse));
```
I would be happy to make a pull request for this but since I am only using tcp connection I am not sure if same changes would be needed for other connection types as well or if it might break some other routines.

To reproduce the bug (1), just run gazebo and spawn iris. It should get stuck on black screen until px4 is launched as well.
To reproduce the bug (2), run gazebo, spawn robot, delete robot, and then spawn again. The gazebo server should raise abort signal and return an 'Address already in use' error (The error is not currently printed which I think should be updated as well) at bind() in gazebo_mavlink_interface.

Thanks!

**Comment by TSC21** [comment]
@saifullah3396 a PR is welcomed, yes. Thank you!

@julianoes FYI

**Comment by julianoes** [comment]
@saifullah3396 thanks for the issue. I think what you found is correct, and I would welcome a pull request to make this less crash-prone :smile:!

**Comment by saifullah3396** [comment]
@TSC21 @julianoes I'm working on it! I have solved the mentioned problems but it seems as a consequence of removing the blocking calls, a lot more issues are arising. In any case, I'll keep you guys updated with its status! :)

**Comment by saifullah3396** [comment]
@TSC21 @julianoes I have resolved the issues at least for TCP connections (I have yet to even use any other config). The px4 can now disconnect/reconnect with the robot any time without messing with gazebo! :)

However, I think it might have caused some conflicts with other functionality such as for HIL mode or serial_enabled case (I have tried to make sure they don't mess with each other but I might have made a mistake somewhere). Sp could you guys let me know of any necessary steps I should take to make sure that they are working the way they were before the update before making a PR?

**Comment by TSC21** [comment]
> @TSC21 @julianoes I have resolved the issues at least for TCP connections (I have yet to even use any other config). The px4 can now disconnect/reconnect with the robot any time without messing with gazebo! :)
> 
> However, I think it might have caused some conflicts with other functionality such as for HIL mode or serial_enabled case (I have tried to make sure they don't mess with each other but I might have made a mistake somewhere). Sp could you guys let me know of any necessary steps I should take to make sure that they are working the way they were before the update before making a PR?

The question is: have you tested HIL? :)

**Comment by saifullah3396** [comment]
No I have not since I don't have a real hardware available atm.

**Comment by julianoes** [comment]
I can test that for you if you submit a pull request.

**Comment by saifullah3396** [comment]
Alright I will do that!

**Comment by saifullah3396** [comment]
Hey @julianoes, can you also let me know the significance of the timeout at the following line?
`gazebo_mavlink_interface.cpp:1150: int timeout_ms = (received_first_actuator_ && enable_lockstep_) ? 1000 : 0;`

Do you think it's still significant for lockstep mode to wait 1000 ms? since with my solution the socket is non-blocking anyway so in my opinion, the code shouldn't stop here for any message... and just keep looking for new message in the next iteration. 

I came across this problem when I was sending commands through offboard control to px4. The commands work fine but if I suddenly interrupt them, the simulation gets stuck (or basically very slow, since polling gets blocked for 1000 ms every iteration or so I believe) which I'm not sure why. As shown, for example, on sending the actuator control commands the robot rises, and if I just interrupt the commands, the simulation real-time factor gradually drops from 1.0 to 0.0. However, keeping the timeout to 0 fixes the problem and robot just falls down as soon as the commands are interrupted.
![Screenshot from 2019-11-05 15-02-01](https://user-images.githubusercontent.com/20021453/68198376-b6214600-ffdd-11e9-8529-749757f05031.png).

Since I'm not entirely sure what lockstep is doing, how do you think this should be treated? Thanks!

**Comment by julianoes** [comment]
@saifullah3396 please read the doc about lockstep, maybe that will make it clearer:
https://dev.px4.io/v1.9.0/en/simulation/index.html#lockstep-simulation

**Comment by saifullah3396** [comment]
@julianoes Thanks! I'll read up on that.
