### ISSUE TITLE
rosrun mavros mavsafety arm Request failed

### ISSUE THREAD

**Issue by sagardalai** [PX4/PX4-SITL_gazebo-classic#366]
Hello everyone,

i launch roslaunch px4 mavros_posix_sitl.launch
it launched perfectly.

and after that I try this rosrun mavros mavsafety arm
And getting error
Request failed. Check mavros logs

And also diagnotics also not working.
and there is no connection between gazebo and mavros in rqt graph and indicating there is no connection between px4 and vehicle.

Please help me out if anyone have solution for this.

**Comment by Jaeyoung-Lim** [comment]
@sagardalai This seems to be a issue with your mavros command line application and not an issue related to this repo
