### ISSUE TITLE
Firmware version is weird number

### ISSUE THREAD

**Issue by tuloski** [PX4/PX4-SITL_gazebo-classic#370]
When I run the simulation with gazebo and mavros (using IRIS model), on QGC I see a weird version for the firmware (something like 48.3.4). Where is this number coming from and why is it there? Should't it be related to the PX4/Firmware, so something like 1.9.2?

**Comment by TSC21** [comment]
That's nothing that could be solved in sitl_gazebo. Please bring that issue to the Firmware side.
