### ISSUE TITLE
Increase update rate in gazebo_mavlink_interface.cpp

### ISSUE THREAD

**Issue by waytry** [PX4/PX4-SITL_gazebo-classic#378]
I am trying to implement a trajectory tracking in a quadcopter using PX4 SITL. PX4 communicate the quadcopter model in SITL through the plugin gazebo_mavlink_interface.cpp. I found that the max update rate is fixed to 250Hz in the [gazebo_mavlink_interface.cpp](https://github.com/PX4/sitl_gazebo/blob/master/src/gazebo_mavlink_interface.cpp#L232). However, in my application I need a higher update rate, e.g. 1000Hz, to improve the tracking performance. How can I modify the __gazebo_mavlink_interface.cpp__ to achieve a higher update rate?

Thanks in advance.

**Comment by Jaeyoung-Lim** [comment]
@waytry If you increase the communication bandwidth, this does not necessarily mean that the rest of the control loop that takes those messages will be faster. Why do you need such a high input rate? This will also be unrealistic for real hardware

**Comment by TSC21** [comment]
@waytry any updates?

**Comment by Jaeyoung-Lim** [comment]
Closing since there were no response. Please reopen if there is any updates
