### ISSUE TITLE
Can I run sitl without ekf2?

### ISSUE THREAD

**Issue by heleidsn** [PX4/PX4-SITL_gazebo-classic#379]
Hello, I am working on a project with PX4 and reinforcement learning, so I need to reset the gazebo world frequently. Is there any idea of using the gazebo ground truth position rather than the estimated position from ekf2? Thanks.

**Comment by Jaeyoung-Lim** [comment]
@heleidsn You can get the groundtruth position directly if you are using ROS using the gazebo_ros package. You can find the information [here](http://gazebosim.org/tutorials?cat=connect_ros)

**Comment by petertheprocess** [comment]
@heleidsn I think these will be helpful.
`def get_odom():
    try:
        handle = rospy.ServiceProxy('gazebo/get_model_state',GetModelState)
        response = handle('iris','ground_plane')
        return response
    except rospy.ServiceException, e:
        print "Service call failed: %s"%e`
