### ISSUE TITLE
Help with Simulink-Gazebo co-simulation

### ISSUE THREAD

**Issue by iftahnaf** [PX4/PX4-SITL_gazebo-classic#410]
Hi all,
in Simulink 2019b, there is a way to perform co-simulation with gazebo, and they even made nice toolbox for it.
I want to use Simulink to design some controllers and then implement it with the sitl on gazebo.
I know that some lines need to be added to the .world files, but I need some help to understand what exactly I need to do.
Thanks for the help,
Iftach.

**Comment by TSC21** [comment]
@iftahnaf the dev team is not actively supporting the Simulink interaction. You will probably have more look if you ask on the Matlab/Simulink forums or directly to Mathworks support.
I don't know if this helps, but there seems to be documentation regarding it: https://www.mathworks.com/help/robotics/examples/perform-co-simulation-between-simulink-and-gazebo.html
