### ISSUE TITLE
gimbal controller plugin yaw setpoint race condition

### ISSUE THREAD

**Issue by jannsta1** [PX4/PX4-SITL_gazebo-classic#422]
I noticed that the yaw axis is quite jittery in the typhoon_h480 model when the aircraft rotates so that it is not aligned with its starting orientation. After some investigation I found that this is because it is possible for a new OnYawStringMsg to set `this->yawCommand` back to (typically) 0 before yawLimited is set for the route. I.e. Before:

https://github.com/PX4/sitl_gazebo/blob/8794a7067ab307d6919a85f7743abbc7836e64fd/src/gazebo_gimbal_controller_plugin.cpp#L487-L489

or 
https://github.com/PX4/sitl_gazebo/blob/8794a7067ab307d6919a85f7743abbc7836e64fd/src/gazebo_gimbal_controller_plugin.cpp#L497-L499

By replacing https://github.com/PX4/sitl_gazebo/blob/8794a7067ab307d6919a85f7743abbc7836e64fd/src/gazebo_gimbal_controller_plugin.cpp#L477 with `double this_yaw = this->yawCommand + this->lastImuYaw;` and using this temporary variable throughout the function the problem is resolved, albeit in a hacky fashion.

**Comment by LorenzMeier** [comment]
Thanks for reporting this!

**Comment by m1baldwin** [comment]
@jannsta1 This was helpful to fix a problem I was having with shaking in the yaw axis, thanks. Here are couple screen captures of the difference I noticed after/before making the recommended edits.

![without_race_condition](https://user-images.githubusercontent.com/35272783/78265807-f3c5c480-74d2-11ea-9419-0dee1ecff4b3.gif)
![with_race_condition](https://user-images.githubusercontent.com/35272783/78265820-f4f6f180-74d2-11ea-97e0-d5bdf01e25f8.gif)

**Comment by LorenzMeier** [comment]
@MaEtUgR Could you please follow up on this with @Jaeyoung-Lim ?
