### ISSUE TITLE
How Can I Specify Vehicle Parameters (Startup File) in v1.9.2

### ISSUE THREAD

**Issue by petertheprocess** [PX4/PX4-SITL_gazebo-classic#428]
Hi.
I would like to reset some parameters  a PX4 SITL setup. Those files used to be, for example, in
```
Firmware/posix-configs/SITL/init/ekf2
```
This used to be in v1.8.2
But in v1.9.2,these files disappeared.
So,I want to konw how can I do it in the new version.
Thanks.

**Comment by TSC21** [comment]
https://dev.px4.io/master/en/simulation/#scripts
