### ISSUE TITLE
how to completely remove gazebo and ros melodic for a new clean install

### ISSUE THREAD

**Issue by AhmedHisham1** [PX4/PX4-SITL_gazebo-classic#443]
I think that due to multiple installations, I get very weird errors when ``` make px4_sitl gazebo ```

I want to remove everything and re-install a clean installation.

**Comment by TSC21** [comment]
This is not an explicit problem. If you have problems with the build, you should report it correctly and we the error output you are getting. Please use discuss.px4.io and use awareness to it in the PX4 Slack channels.
