### ISSUE TITLE
McMillan airfields model has terrain above ground

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [PX4/PX4-SITL_gazebo-classic#444]
When running the Mcmillan airfields world the terrain is above the ground. The world was added in #406 

Therefore the vehicle gets spawned under the terrain.

![Screenshot from 2020-03-26 12-22-20(1)](https://user-images.githubusercontent.com/5248102/77664136-312fcc80-6f7e-11ea-81fa-5acfe4458b59.png)

I tried defining the `pose` of the model, but with the heightmap it doesn't seem to move

@ahcorde Any ideas how to solve this?

**Comment by tfoote** [comment]
As my comment here: https://github.com/PX4/sitl_gazebo/pull/406#issuecomment-604750827

Should the origin have altitude 0 if it's supposed to be at MSL?

**Comment by TSC21** [comment]
> As my comment here: [#406 (comment)](https://github.com/PX4/sitl_gazebo/pull/406#issuecomment-604750827)
> 
> Should the origin have altitude 0 if it's supposed to be at MSL?

IMHO I think that it makes sense the elevation is set at 280m, if 280m is the AMSL. It means that the aircraft will start at 280m AMSL if it spawns at 0,0,0.

**Comment by Jaeyoung-Lim** [comment]
This was fixed in the model database
