### ISSUE TITLE
Gimbal controller buggy

### ISSUE THREAD

**Issue by jgoppert** [PX4/PX4-SITL_gazebo-classic#49]
The gimbal controller has some odd behaviours at different compass headings. I added an angle wrap for the error calculation, and that helped some. Also the euler angles are assumed to be 321, but I'm creating a model of the tarot t4-3d, which has angles 312, so might need to think about how best to handle that.

**Comment by jgoppert** [comment]
Looks like that the wrap issue wa fixed, support for 312 would still be nice.

**Comment by hsu** [comment]
For 312 support, is [QtoZXY](https://github.com/PX4/sitl_gazebo/blob/master/src/gazebo_gimbal_controller_plugin.cpp#L312) what you need?

**Comment by jgoppert** [comment]
Great, seems you guys already fixed all of this and I just didn't pull recently on my branch.
