### ISSUE TITLE
When changing a world in Gazebo, the drone model is duplicated.

### ISSUE THREAD

**Issue by petergerten** [PX4/PX4-SITL_gazebo-classic#503]
To reproduce:
```
1. make px4_sitl gazebo_typhoon_h480
2. Change something in the world
3. "save"
4. Start gazebo with the modified world file
```
Now there are too h480 on top of each other.
sitl_gazebo seems to instantiate the drone independently from the world file.
I noticed that I can manually delete the definition for the h480 model in the file and it works. 
But how would I for example change the pose of the model? (i.e. start from the balcony of a house)

**Comment by petergerten** [comment]
Switching from Gazebo 9 to Gazebo 10 fixed this.

**Comment by Jaeyoung-Lim** [comment]
@petergerten Editing worlds through gazebo client is not a supported usecase

**Comment by petergerten** [comment]
@Jaeyoung-Lim thanks, I will keep that in mind.
