### ISSUE TITLE
Typhoon H480 vehilce is rotated by PI

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [PX4/PX4-SITL_gazebo-classic#511]
I noticed that on the typhoon h480 vehicle, the vehicle is rotated by pi.

When the vehicle is placed as below, the `yaw=0`.

![image](https://user-images.githubusercontent.com/5248102/83971021-3cd23480-a8d9-11ea-8ea8-0b7fb22a06cc.png)

This seems to be compensated by the fact that the imu is roated by pi here: https://github.com/PX4/sitl_gazebo/blob/master/models/typhoon_h480/typhoon_h480.sdf#L678

Also similar to this on the gimbal of the h480 the camera sensor is rotated by pi: https://github.com/PX4/sitl_gazebo/blob/master/models/typhoon_h480/typhoon_h480.sdf#L387

**Comment by LorenzMeier** [comment]
Interesting - I would revert all that so that its less confusing.
