### ISSUE TITLE
Unable to connect to custom designed hexrotor

### ISSUE THREAD

**Issue by deepak-1530** [PX4/PX4-SITL_gazebo-classic#518]
I have written the code for a custom hexrotor and have followed the typhoon_h480 model for the same. Inspite of adding the mavlink plugins in the SDF file I am not able to connect to the drone.

**Comment by TSC21** [comment]
@deepak-1530 hi! What do you mean with not being able to connect the drone? Have you created the respective init.d posix initialization file in the PX4 Firmware side? Also, have you created a mixer for that configuration or are you using the same as the Typhoon?

**Comment by deepak-1530** [comment]
When i do make px4_sitl gazebo, it shows

INFO  [px4_work_queue] creating: wq:hp_default, priority: 87, stack: 16384 bytes
INFO  [px4_work_queue] creating: wq:att_pos_ctrl, priority: 88, stack: 16384 bytes
INFO  [px4_work_queue] creating: wq:rate_ctrl, priority: 99, stack: 16384 bytes
INFO  [init] Mixer: etc/mixers/quad_w.main.mix on /dev/pwm_output0
INFO  [mavlink] mode: Normal, data rate: 4000000 B/s on udp port 14570 remote port 14550

After this, nothing happens. 
I have created the init.d posix initialization file. For the mixer, I have used the same as typhoon. It will be amazing if you can tell me how to create one.

**Comment by TSC21** [comment]
> When i do make px4_sitl gazebo, it shows
> 
> INFO [px4_work_queue] creating: wq:hp_default, priority: 87, stack: 16384 bytes
> INFO [px4_work_queue] creating: wq:att_pos_ctrl, priority: 88, stack: 16384 bytes
> INFO [px4_work_queue] creating: wq:rate_ctrl, priority: 99, stack: 16384 bytes
> INFO [init] Mixer: etc/mixers/quad_w.main.mix on /dev/pwm_output0
> INFO [mavlink] mode: Normal, data rate: 4000000 B/s on udp port 14570 remote port 14550
> 
> After this, nothing happens.
> I have created the init.d posix initialization file. For the mixer, I have used the same as typhoon. It will be amazing if you can tell me how to create one.

To start the configuration you want, `make px4_sitl gazebo` is not enough, since that will spawn the Iris model by default. Have you add your aircraft as a CMake target?

**Comment by deepak-1530** [comment]
Yes I have done that as well. In the iris.world file, I have used my custom drone model instead of iris drone. I am getting my drone in the gazebo world but unable to connect to it over mavlink

**Comment by deepak-1530** [comment]
![px4](https://user-images.githubusercontent.com/43798160/84588410-c9827280-ae44-11ea-83a0-aaafd5ca58bd.png)
I followed these steps.

**Comment by Jaeyoung-Lim** [comment]
@deepak-1530 Any updates?

**Comment by deepak-1530** [comment]
Hello @Jaeyoung-Lim I updated the SDF file of typhoon (with our own meshes generated from the SolidWorks model) and also changed the parameters in mixer file to get my own drone model as i couldn't get the original file to work.

**Comment by Jaeyoung-Lim** [comment]
@deepak-1530 Sounds like you made it work in the end. Congratulations!

Can we close this issue in that case?

**Comment by deepak-1530** [comment]
Yes. I'll close it
