### ISSUE TITLE
How to  add the lidar to iris

### ISSUE THREAD

**Issue by wangwenha** [PX4/PX4-SITL_gazebo-classic#548]
i  want to add lidar to iris in `multi_uav_mavros_sitl.launch`,i chaneg the  `vehicle spawn`file into `2Dlidar_px4.launch`
`<launch>
    
    <arg name="x" default="0"/>
    <arg name="y" default="0"/>
    <arg name="z" default="0"/>
    <arg name="R" default="0"/>
    <arg name="P" default="0"/>
    <arg name="Y" default="0"/>
	
    <arg name="px4_config" default="$(find simulation)/resource/px4_config.yaml" />
    <arg name="world_path" default="$(find simulation)/worlds/empty_room.world" />
    <arg name="gui" default="true"/>
    <arg name="ns" default="/"/>
    <arg name="model" default="iris_2Dlidar"/>
    <arg name="fcu_url" default="udp://:14540@localhost:14557"/>
    <arg name="gcs_url" default="" />   
    <arg name="tgt_system" default="1" />
    <arg name="tgt_component" default="1" />
    <arg name="vehicle" default="iris"/>

    <param name="use_sim_time" value="true" />

  
  <node pkg="tf" type="static_transform_publisher" name="tf_2Dlidar"
          args="0 0 0 3.1415926 0 0 base_link 2Dlidar_link 10"/>

    
    
    
            

    
    

    
    <node name="spawn_model" pkg="gazebo_ros" type="spawn_model" output="screen"
          args="-sdf -database $(arg model) -model $(arg vehicle)  -x $(arg x) -y $(arg y) -z $(arg z) -R $(arg R) -P $(arg P) -Y $(arg Y)">
    </node>

</launch>`

**Comment by Jaeyoung-Lim** [comment]
You can look at https://github.com/PX4/sitl_gazebo/blob/master/models/iris_opt_flow/iris_opt_flow.sdf as an example
