### ISSUE TITLE
PX4 simulation in Gazebo

### ISSUE THREAD

**Issue by DeanJJJ** [PX4/PX4-SITL_gazebo-classic#56]
anyone know how to simulate PX4 in Gazebo? when I enter "make posix_sitl_default gazebo", the error which is 
CMakeFiles/Makefile2:9960: recipe for target 'src/firmware/posix/CMakeFiles/gazebo.dir/rule' failed
make[2]: **\* [src/firmware/posix/CMakeFiles/gazebo.dir/rule] Error 2
Makefile:3497: recipe for target 'gazebo' failed
make[1]: **\* [gazebo] Error 2
Makefile:160: recipe for target 'posix_sitl_default' failed
make: **\* [posix_sitl_default] Error 2
will appear.

**Comment by julianoes** [comment]
@DeanJJJ Can you please post the whole output of make and the output of

```
git rev-parse HEAD
```

**Comment by DeanJJJ** [comment]
@julianoes thank you for reply! The following is the output of ' git rev-parse HEAD '
db44129ec099a05debf9187da2fd09035c9a67d7

**Comment by DeanJJJ** [comment]
@julianoes and the following is the while output of make 
PX4 CONFIG: /home/ubuntu/src/Firmware/build_posix_sitl_default
[  0%] Built target git_genmsg
[  0%] Built target prebuild_targets
[  1%] Built target git_gencpp
[  1%] Performing configure step for 'sitl_gazebo'
[  1%] Built target git_uavcan
[  2%] Built target git_mavlink
[  2%] Built target git_matrix
-- install-prefix: /usr
[  2%] Built target git_driverframework
[  2%] Built target git_jmavsim
[  2%] Built target git_ecl
[  4%] Built target df_driver_framework
[  4%] Built target git_gazebo
[  4%] Built target mixer_gen
[  5%] Built target xml_gen
[ 24%] Built target msg_gen
[ 25%] Built target platforms__common
[ 26%] Built target generate_topic_listener
CMake Error at CMakeLists.txt:23 (find_package):
  By not providing "Findgazebo.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "gazebo", but
  CMake did not find one.

  Could not find a package configuration file provided by "gazebo" with any
  of the following names:

```
gazeboConfig.cmake
gazebo-config.cmake
```

  Add the installation prefix of "gazebo" to CMAKE_PREFIX_PATH or set
  "gazebo_DIR" to a directory containing one of the above files.  If "gazebo"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/src/Firmware/build_posix_sitl_default/build_gazebo/CMakeFiles/CMakeOutput.log".
src/firmware/posix/CMakeFiles/sitl_gazebo.dir/build.make:105: recipe for target 'external/Stamp/sitl_gazebo/sitl_gazebo-configure' failed
make[4]: **\* [external/Stamp/sitl_gazebo/sitl_gazebo-configure] Error 1
CMakeFiles/Makefile2:9086: recipe for target 'src/firmware/posix/CMakeFiles/sitl_gazebo.dir/all' failed
make[3]: **\* [src/firmware/posix/CMakeFiles/sitl_gazebo.dir/all] Error 2
make[3]: **\* Waiting for unfinished jobs....
[ 26%] Built target drivers__boards__sitl
[ 28%] Built target drivers__device
[ 35%] Built target systemcmds__tests
CMakeFiles/Makefile2:9960: recipe for target 'src/firmware/posix/CMakeFiles/gazebo.dir/rule' failed
make[2]: **\* [src/firmware/posix/CMakeFiles/gazebo.dir/rule] Error 2
Makefile:3497: recipe for target 'gazebo' failed
make[1]: **\* [gazebo] Error 2
Makefile:160: recipe for target 'posix_sitl_default' failed
make: **\* [posix_sitl_default] Error 2

**Comment by LorenzMeier** [comment]
You don't have all Gazebo packages installed. Please go back to the PX4 Linux installation instructions and make sure to install _everything_.

**Comment by julianoes** [comment]
@DeanJJJ please update to latest master. There have been fixes for gazebo:

https://github.com/PX4/Firmware/commit/2d039af7a4299c6565e0d47f333adad65fd0c0a0

**Comment by DeanJJJ** [comment]
@julianoes  thx a lot, I will try it.

**Comment by DeanJJJ** [comment]
@julianoes sorry for bothering again. I have updated firmware to latest master and installed Gazebo packages step by step. However, new errors appear after 100% building. Errors is shown below:

[100%] Completed 'sitl_gazebo'
[100%] Built target sitl_gazebo
Scanning dependencies of target gazebo
args: /home/ubuntu/src/Firmware/build_posix_sitl_default/src/firmware/posix/px4 posix-configs/SITL/init/lpe none gazebo none /home/ubuntu/src/Firmware /home/ubuntu/src/Firmware/build_posix_sitl_default
SITL ARGS
sitl_bin: /home/ubuntu/src/Firmware/build_posix_sitl_default/src/firmware/posix/px4
rcS_dir: posix-configs/SITL/init/lpe
debugger: none
program: gazebo
model: none
src_path: /home/ubuntu/src/Firmware
build_path: /home/ubuntu/src/Firmware/build_posix_sitl_default
empty model, setting iris as default
/home/ubuntu/src/Firmware/Tools/sitl_run.sh: line 58: kill: ubuntu: arguments must be process or job IDs
src/firmware/posix/CMakeFiles/gazebo.dir/build.make:57: recipe for target 'src/firmware/posix/CMakeFiles/gazebo' failed
make[4]: **\* [src/firmware/posix/CMakeFiles/gazebo] Error 1
CMakeFiles/Makefile2:10004: recipe for target 'src/firmware/posix/CMakeFiles/gazebo.dir/all' failed
make[3]: **\* [src/firmware/posix/CMakeFiles/gazebo.dir/all] Error 2
CMakeFiles/Makefile2:10011: recipe for target 'src/firmware/posix/CMakeFiles/gazebo.dir/rule' failed
make[2]: **\* [src/firmware/posix/CMakeFiles/gazebo.dir/rule] Error 2
Makefile:3510: recipe for target 'gazebo' failed
make[1]: **\* [gazebo] Error 2
Makefile:160: recipe for target 'posix_sitl_default' failed
make: **\* [posix_sitl_default] Error 2

**Comment by julianoes** [comment]
Debug what goes wrong here:

```
/home/ubuntu/src/Firmware/Tools/sitl_run.sh: line 58: kill: ubuntu: arguments must be process or job IDs
```

**Comment by DeanJJJ** [comment]
@julianoes it works, thank you

**Comment by xaviruvpadhiyar98** [comment]
CMakeFiles/Makefile2:6216: recipe for target 'modules/videoio/CMakeFiles/opencv_videoio.dir/all' failed
make[1]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by xaviruvpadhiyar98** [comment]
make -j4
[  1%] Built target opencv_core_pch_dephelp
[  1%] Built target opencv_perf_core_pch_dephelp
[  3%] Built target libwebp
[  4%] Built target opencv_imgcodecs_pch_dephelp
[  4%] Built target opencv_imgproc_pch_dephelp
[  4%] Built target opencv_videoio_pch_dephelp
[  5%] Built target opencv_highgui_pch_dephelp
[  6%] Built target IlmImf
[  6%] Built target opencv_ts_pch_dephelp
[  6%] Built target opencv_test_core_pch_dephelp
[  6%] Built target opencv_test_flann_pch_dephelp
[  8%] Built target opencv_flann_pch_dephelp
[  8%] Built target opencv_perf_imgproc_pch_dephelp
[  8%] Built target opencv_test_imgproc_pch_dephelp
[  9%] Built target opencv_test_ml_pch_dephelp
[  9%] Built target opencv_ml_pch_dephelp
[  9%] Built target opencv_photo_pch_dephelp
[  9%] Built target opencv_perf_photo_pch_dephelp
[  9%] Built target opencv_reg_pch_dephelp
[  9%] Built target opencv_test_photo_pch_dephelp
[  9%] Built target opencv_test_reg_pch_dephelp
[  9%] Built target opencv_perf_reg_pch_dephelp
[  9%] Built target opencv_surface_matching_pch_dephelp
[  9%] Built target opencv_video_pch_dephelp
[  9%] Built target opencv_test_video_pch_dephelp
[  9%] Built target opencv_perf_video_pch_dephelp
[  9%] Built target opencv_dnn_pch_dephelp
[  9%] Built target opencv_test_dnn_pch_dephelp
[  9%] Built target opencv_fuzzy_pch_dephelp
[ 10%] Built target libprotobuf
[ 10%] Built target opencv_test_fuzzy_pch_dephelp
[ 11%] Built target opencv_perf_imgcodecs_pch_dephelp
[ 11%] Built target opencv_test_imgcodecs_pch_dephelp
[ 12%] Built target opencv_shape_pch_dephelp
[ 12%] Built target opencv_test_shape_pch_dephelp
[ 12%] Built target opencv_test_videoio_pch_dephelp
[ 12%] Built target opencv_perf_videoio_pch_dephelp
[ 12%] Built target opencv_test_highgui_pch_dephelp
[ 12%] Built target opencv_objdetect_pch_dephelp
[ 12%] Built target opencv_perf_objdetect_pch_dephelp
[ 12%] Built target opencv_test_objdetect_pch_dephelp
[ 12%] Built target opencv_superres_pch_dephelp
[ 12%] Built target opencv_plot_pch_dephelp
[ 12%] Built target opencv_perf_superres_pch_dephelp
[ 12%] Built target opencv_test_superres_pch_dephelp
[ 12%] Built target opencv_xobjdetect_pch_dephelp
[ 13%] Built target opencv_test_xphoto_pch_dephelp
[ 13%] Built target opencv_perf_xphoto_pch_dephelp
[ 13%] Built target opencv_bgsegm_pch_dephelp
[ 13%] Built target opencv_test_bgsegm_pch_dephelp
[ 13%] Built target opencv_bioinspired_pch_dephelp
[ 13%] Built target opencv_test_bioinspired_pch_dephelp
[ 13%] Built target opencv_perf_bioinspired_pch_dephelp
[ 13%] Built target opencv_dpm_pch_dephelp
[ 13%] Built target opencv_face_pch_dephelp
[ 13%] Built target opencv_features2d_pch_dephelp
[ 13%] Built target opencv_test_features2d_pch_dephelp
[ 13%] Built target opencv_perf_features2d_pch_dephelp
[ 13%] Built target opencv_perf_line_descriptor_pch_dephelp
[ 13%] Built target opencv_line_descriptor_pch_dephelp
[ 13%] Built target opencv_test_line_descriptor_pch_dephelp
[ 13%] Built target opencv_saliency_pch_dephelp
[ 13%] Built target opencv_text_pch_dephelp
[ 13%] Built target opencv_calib3d_pch_dephelp
[ 13%] Built target opencv_test_calib3d_pch_dephelp
[ 15%] Built target opencv_perf_calib3d_pch_dephelp
[ 16%] Built target opencv_ccalib_pch_dephelp
[ 16%] Built target opencv_rgbd_pch_dephelp
[ 16%] Built target opencv_test_rgbd_pch_dephelp
[ 16%] Built target opencv_stereo_pch_dephelp
[ 16%] Built target opencv_test_stereo_pch_dephelp
[ 16%] Built target opencv_perf_stereo_pch_dephelp
[ 16%] Built target opencv_structured_light_pch_dephelp
[ 16%] Built target opencv_tracking_pch_dephelp
[ 16%] Built target opencv_test_structured_light_pch_dephelp
[ 16%] Built target opencv_perf_tracking_pch_dephelp
[ 16%] Built target opencv_test_tracking_pch_dephelp
[ 16%] Built target opencv_videostab_pch_dephelp
[ 16%] Built target opencv_perf_xfeatures2d_pch_dephelp
[ 16%] Built target opencv_xfeatures2d_pch_dephelp
[ 17%] Built target opencv_test_xfeatures2d_pch_dephelp
[ 17%] Built target opencv_perf_ximgproc_pch_dephelp
[ 17%] Built target opencv_ximgproc_pch_dephelp
[ 18%] Built target opencv_aruco_pch_dephelp
[ 18%] Built target opencv_test_ximgproc_pch_dephelp
[ 18%] Built target opencv_test_aruco_pch_dephelp
[ 18%] Built target opencv_optflow_pch_dephelp
[ 18%] Built target opencv_test_optflow_pch_dephelp
[ 18%] Built target opencv_stitching_pch_dephelp
[ 18%] Built target opencv_test_stitching_pch_dephelp
[ 18%] Built target opencv_perf_stitching_pch_dephelp
[ 18%] Built target pch_Generate_opencv_core
[ 18%] Built target pch_Generate_opencv_perf_core
[ 18%] Built target pch_Generate_opencv_imgcodecs
[ 18%] Built target pch_Generate_opencv_videoio
[ 18%] Built target pch_Generate_opencv_imgproc
[ 18%] Built target pch_Generate_opencv_highgui
[ 18%] Built target pch_Generate_opencv_ts
[ 18%] Built target pch_Generate_opencv_test_core
[ 18%] Built target pch_Generate_opencv_flann
[ 18%] Built target pch_Generate_opencv_test_imgproc
[ 18%] Built target pch_Generate_opencv_test_flann
[ 18%] Built target pch_Generate_opencv_perf_imgproc
[ 18%] Built target pch_Generate_opencv_ml
[ 18%] Built target pch_Generate_opencv_test_ml
[ 18%] Built target pch_Generate_opencv_photo
[ 18%] Built target pch_Generate_opencv_perf_photo
[ 18%] Built target pch_Generate_opencv_test_photo
[ 18%] Built target pch_Generate_opencv_reg
[ 18%] Built target pch_Generate_opencv_test_reg
[ 19%] Built target pch_Generate_opencv_surface_matching
[ 19%] Built target pch_Generate_opencv_perf_reg
[ 19%] Built target pch_Generate_opencv_video
[ 20%] Built target pch_Generate_opencv_test_video
[ 20%] Built target pch_Generate_opencv_dnn
[ 20%] Built target pch_Generate_opencv_perf_video
[ 20%] Built target pch_Generate_opencv_fuzzy
[ 20%] Built target pch_Generate_opencv_test_dnn
[ 20%] Built target pch_Generate_opencv_test_fuzzy
[ 20%] Built target pch_Generate_opencv_perf_imgcodecs
[ 20%] Built target pch_Generate_opencv_test_imgcodecs
[ 20%] Built target pch_Generate_opencv_shape
[ 20%] Built target pch_Generate_opencv_test_videoio
[ 20%] Built target pch_Generate_opencv_test_shape
[ 20%] Built target pch_Generate_opencv_perf_videoio
[ 20%] Built target pch_Generate_opencv_test_highgui
[ 20%] Built target pch_Generate_opencv_objdetect
[ 20%] Built target pch_Generate_opencv_test_objdetect
[ 20%] Built target pch_Generate_opencv_perf_objdetect
[ 20%] Built target pch_Generate_opencv_test_superres
[ 20%] Built target pch_Generate_opencv_plot
[ 20%] Built target pch_Generate_opencv_superres
[ 20%] Built target pch_Generate_opencv_perf_superres
[ 22%] Built target pch_Generate_opencv_xobjdetect
[ 22%] Built target pch_Generate_opencv_test_xphoto
[ 22%] Built target pch_Generate_opencv_perf_xphoto
[ 22%] Built target pch_Generate_opencv_test_bgsegm
[ 22%] Built target pch_Generate_opencv_bgsegm
[ 22%] Built target pch_Generate_opencv_test_bioinspired
[ 22%] Built target pch_Generate_opencv_bioinspired
[ 22%] Built target pch_Generate_opencv_perf_bioinspired
[ 22%] Built target pch_Generate_opencv_dpm
[ 22%] Built target pch_Generate_opencv_face
[ 23%] Built target pch_Generate_opencv_features2d
[ 23%] Built target pch_Generate_opencv_test_features2d
[ 24%] Built target pch_Generate_opencv_perf_features2d
[ 24%] Built target pch_Generate_opencv_line_descriptor
[ 24%] Built target pch_Generate_opencv_perf_line_descriptor
[ 25%] Built target pch_Generate_opencv_test_line_descriptor
[ 25%] Built target pch_Generate_opencv_saliency
[ 25%] Built target pch_Generate_opencv_text
[ 25%] Built target pch_Generate_opencv_calib3d
[ 25%] Built target pch_Generate_opencv_test_calib3d
[ 25%] Built target pch_Generate_opencv_perf_calib3d
[ 25%] Built target pch_Generate_opencv_rgbd
[ 25%] Built target pch_Generate_opencv_ccalib
[ 25%] Built target pch_Generate_opencv_test_rgbd
[ 25%] Built target pch_Generate_opencv_stereo
[ 25%] Built target pch_Generate_opencv_test_stereo
[ 25%] Built target pch_Generate_opencv_perf_stereo
[ 25%] Built target pch_Generate_opencv_test_structured_light
[ 25%] Built target pch_Generate_opencv_tracking
[ 25%] Built target pch_Generate_opencv_structured_light
[ 25%] Built target pch_Generate_opencv_perf_tracking
[ 25%] Built target pch_Generate_opencv_videostab
[ 25%] Built target pch_Generate_opencv_test_tracking
[ 26%] Built target pch_Generate_opencv_perf_xfeatures2d
[ 26%] Built target pch_Generate_opencv_xfeatures2d
[ 26%] Built target pch_Generate_opencv_test_xfeatures2d
[ 26%] Built target pch_Generate_opencv_ximgproc
[ 26%] Built target pch_Generate_opencv_test_ximgproc
[ 26%] Built target pch_Generate_opencv_perf_ximgproc
[ 26%] Built target pch_Generate_opencv_test_aruco
[ 26%] Built target pch_Generate_opencv_aruco
[ 26%] Built target pch_Generate_opencv_test_optflow
[ 26%] Built target pch_Generate_opencv_optflow
[ 26%] Built target pch_Generate_opencv_test_stitching
[ 26%] Built target pch_Generate_opencv_stitching
[ 26%] Built target pch_Generate_opencv_perf_stitching
[ 29%] Built target opencv_core
[ 29%] Built target opencv_flann
[ 30%] Built target opencv_ml
[ 30%] Built target opencv_surface_matching
[ 32%] Built target opencv_imgproc
[ 33%] Built target opencv_reg
[ 34%] Built target opencv_video
[ 36%] Built target opencv_imgcodecs
[ 37%] Built target opencv_photo
make[2]: *** No rule to make target '/usr/include/../lib/libavcodec.a', needed by 'lib/libopencv_videoio.so.3.1.0'.  Stop.
CMakeFiles/Makefile2:6216: recipe for target 'modules/videoio/CMakeFiles/opencv_videoio.dir/all' failed
make[1]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 37%] Built target opencv_fuzzy
[ 37%] Built target opencv_shape
[ 38%] Built target opencv_dnn
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2


I m stuck here plz help me

**Comment by kevinuav** [comment]
Hey,guys!
    I encounter an error similar to this issue when I compile for the gazebo with branch master in my  Mac OS X(10.15.3 Catalina).What's the problem?Thank you!

here is the message from terminal:
%make px4_sitl gazebo_standard_vtol
.......
[24/98] Building CXX object CMakeFiles.../liftdrag_plugin/liftdrag_plugin.cpp.o
ninja: build stopped: subcommand failed.
[712/716] Linking CXX executable bin/px4
FAILED: external/Stamp/sitl_gazebo/sitl_gazebo-build 
ninja: build stopped: subcommand failed.
make: *** [px4_sitl] Error 1

**Comment by Francis-Herman** [comment]
home/francis/gpstk/dev/ext/lib/Math/Vector/VectorOperators.hpp:124:7: note: in expansion of macro ‘VecBaseNewBinaryOperator’
  124 |       VecBaseNewBinaryOperator(!=, Vector<bool>)
      |       ^~~~~~~~~~~~~~~~~~~~~~~~
/home/francis/gpstk/dev/ext/lib/Math/Vector/VectorOperators.hpp:104:8: note:   template argument deduction/substitution failed:
  104 | retval operator func(const T l, const ConstVectorBase<T, BaseClass>& r) \
      |        ^~~~~~~~
/home/francis/gpstk/dev/ext/lib/Math/Vector/VectorOperators.hpp:124:7: note: in expansion of macro ‘VecBaseNewBinaryOperator’
hello! 
how do i overcome this error please 

 124 |       VecBaseNewBinaryOperator(!=, Vector<bool>)
      |       ^~~~~~~~~~~~~~~~~~~~~~~~
/home/francis/gpstk/dev/ext/apps/geomatics/JPLeph/testSSEph.cpp:243:18: note:   ‘std::ostream’ {aka ‘std::basic_ostream<char>’} is not derived from ‘const gpstk::ConstVectorBase<T, BaseClass>’
  243 |    if(LOGstrm != cout) cout << PrgmName << " timing: " << fixed << setprecision(9)
      |                  ^~~~
make[2]: *** [ext/apps/geomatics/JPLeph/CMakeFiles/testSSEph.dir/build.make:63: ext/apps/geomatics/JPLeph/CMakeFiles/testSSEph.dir/testSSEph.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1058: ext/apps/geomatics/JPLeph/CMakeFiles/testSSEph.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Comment by Francis-Herman** [comment]
francis@francis-HP-Laptop-15-bs0xx:~/Downloads/source$ ./correctScript
bash: ./correctScript: No such file or directory

how do install the software inside the source folder

**Comment by julianoes** [comment]
Please create new issues and provide all the necessary context, and don't necrobump old threads, thanks.
