### ISSUE TITLE
Formula for subtracting spanwise velocity seems incorrect

### ISSUE THREAD

**Issue by a6a3uh** [PX4/PX4-SITL_gazebo-classic#560]
https://github.com/PX4/sitl_gazebo/blob/2858552ed70c379ac240113373e5f50310d98144/src/liftdrag_plugin/liftdrag_plugin.cpp#L259

As stated in comments above the correct formulae is:
projected = spanwiseI Xcross ( vector Xcross spanwiseI)
this vector triple product could be converted to dot product:
vel - vel.Dot(spanwiseI)*spanwiseI
instead we have following:
vel - vel.Dot(spanwiseI)*velI

Putting it another way. spanwise velocity is velocity projection onto spanwiseI multiplied by spanwise unit vector (not velocity unit vector).

**Comment by Jaeyoung-Lim** [comment]
@a6a3uh Good catch, could you make a PR for the fix?

**Comment by a6a3uh** [comment]
Done https://github.com/PX4/sitl_gazebo/pull/562

**Comment by Jaeyoung-Lim** [comment]
Fixed in #562
