### ISSUE TITLE
PX4 SITL Gazebo Standard_VTOL will not yaw for takeoff and transition

### ISSUE THREAD

**Issue by UASOP** [PX4/PX4-SITL_gazebo-classic#581]
Greetings, 

I am currently working on a project using the PX4 standard VTOL sitl gazebo and noticed a repeating behavior that in order to begin the transition to fixed wing for a VTOL takeoff and transition waypoint, the waypoint has to be directly in front of the SITL standard VTOL. If the waypoint is anywhere other then in front of the aircraft with an azimuth of 090 with some minor deviations in degrees from there, the aircraft will not yaw to face the heading for transition. I have checked the weathervane parameters as well just to see if the WV_YRATE_MAX was set to 0 and it is currently 90. If there any reason why the SITL aircraft is not following the command to yaw to a specific heading before the transition? 

Thanks in advance for he assistance. In the mean time I am going to try to disable the WV_EN parameter to see if that fixes the problem and follow up back here.

**Comment by UASOP** [comment]
Disabling weathervane did not resolve the issue.

**Comment by UASOP** [comment]
Alright so quick update here. I did a quick git checkout of version 1.10.1 and 1.10.2 and the heading changes on the VTOL Standard as needed. The version that I was running with the heading not working was the current master.

**Comment by Jaeyoung-Lim** [comment]
@UASOP I think this is not an issue of the simulation, but the firmware. Please post a issue on the firmware side

**Comment by UASOP** [comment]
@Jaeyoung-Lim  Posted in PX4 Firmware github issue as instructed, closing this issue out for now.
