### ISSUE TITLE
Two advice on wind force for multirotor

### ISSUE THREAD

**Issue by robin-shaun** [PX4/PX4-SITL_gazebo-classic#583]
Hello, I'm glad to see that `relative_wind_velocity` is added to `gazebo_motor_model`. Now it influences 'air_drag' and 'rolling_moment'. However, it doesn't influence the force scalar.
```
#if GAZEBO_MAJOR_VERSION >= 9
  ignition::math::Vector3d body_velocity = link_->WorldLinearVel();
#else
  ignition::math::Vector3d body_velocity = ignitionFromGazeboMath(link_->GetWorldLinearVel());
#endif
  double vel = body_velocity.Length();
  double scalar = 1 - vel / 25.0; // at 50 m/s the rotor will not produce any force anymore
  scalar = ignition::math::clamp(scalar, 0.0, 1.0);
  // Apply a force to the link.
  link_->AddRelativeForce(ignition::math::Vector3d(0, 0, force * scalar));
```
It will be better to change the body_velocity  to relative_wind_velocity as well.

Another advice is that, in 'gazebo_wind_plugin', now the wind force becomes the wind velocity, so the air drag of the fuselage is given up.  For more accuracy, maybe it's better to add liftdrag_plugin to the sdf files as plane does. For example, in 'iris.sdf', we can add code as follow:
```
<plugin name="fuselage" filename="libLiftDragPlugin.so">
      <a0>0.05984281113</a0>
      <cla>4.752798721</cla>
      <cda>0.6417112299</cda>
      <cma>0.0</cma>
      <alpha_stall>0.3391428111</alpha_stall>
      <cla_stall>-3.85</cla_stall>
      <cda_stall>-0.9233984055</cda_stall>
      <cma_stall>0</cma_stall>
      <cp>-0.05 0.45 0.05</cp>
      <area>0.6</area>
      <air_density>1.2041</air_density>
      <forward>1 0 0</forward>
      <upward>0 0 1</upward>
      <link_name>base_link</link_name>
      <control_joint_name>
        left_elevon_joint
      </control_joint_name>
      <control_joint_rad_to_cl>-0.5</control_joint_rad_to_cl>
      <robotNamespace></robotNamespace>
      <windSubTopic>world_wind</windSubTopic>
    </plugin>
```
In this way, we not only bring drag for fuselage, but also bring lift for fuselage. Nowadays, some multirotor considers lift design for fuselage, like this [A Lifting Wing Fixed on Multirotor UAVs for Long Flight Ranges](https://arxiv.org/abs/2006.15579)

**Comment by Jaeyoung-Lim** [comment]
@robin-shaun Thanks for the suggestions. Would it be possible for you to make these suggestions into a pull request?

On the second suggestion, liftdrag plugin only models lift/drag in a single plane that is vertical to the wing surface, therefore it is not applicable for lifting body type aerodynamic effects since the lift drag plane can change.

**Comment by petertheprocess** [comment]
> On the second suggestion, lift_\drag plugin only models lift/drag in a single plane that is vertical to the wing surface, therefore it is not applicable for lifting body type aerodynamic effects since the lift drag plane can change.

Why is this not applicable? For lifting body, the lift and drag are also changing with the AOA, of course,  it can be seen as an additional wing surface. Right? Or did I misunderstand your meaning?

**Comment by Jaeyoung-Lim** [comment]
@petertheprocess Right, I meant that the dominant lift direction are not always vertical to the vehicle since there are a lot of forces (e.g. side slip forces, aerodynamic moments on other axis) and these are not modeled in the liftdrag plugin.

Probably we want to keep it simple to keep it efficient but "good enough" for modeling the wing as an element. (lift-drag on a single plane with a one axis moment)

**Comment by Osama-Mamdouh** [comment]
> Right, I meant that the dominant lift direction are not always vertical to the vehicle since there are a lot of forces (e.g. side slip forces, aerodynamic moments on other axis) and these are not modeled in the liftdrag plugin.
> 
> Probably we want to keep it simple to keep it efficient but "good enough" for modeling the wing as an element. (lift-drag on a single plane with a one axis moment)

Can we use the Liftdrag plugin to calculate the drag coefficient for the fuselage (body) of a multi-rotor?
