### ISSUE TITLE
Alternate world

### ISSUE THREAD

**Issue by Kush0301** [PX4/PX4-SITL_gazebo-classic#591]
The default world in the mavros_posix_sitl.launch file  empty.world
If I change the world in the launch file to iris.world, I get the following error:

`[gazebo-3] process has died [pid 5608, exit code 127, cmd /opt/ros/melodic/lib/gazebo_ros/gzserver -e ode /home/kushagra/catkin_ws/src/Firmware/Tools/sitl_gazebo/worlds/iris.world __name:=gazebo __log:=/home/kushagra/.ros/log/2f743e76-e7c4-11ea-9474-646e69a80395/gazebo-3.log].
log file: /home/kushagra/.ros/log/2f743e76-e7c4-11ea-9474-646e69a80395/gazebo-3*.log
[gazebo_gui-4] process has died [pid 5610, exit code 127, cmd /opt/ros/melodic/lib/gazebo_ros/gzclient __name:=gazebo_gui __log:=/home/kushagra/.ros/log/2f743e76-e7c4-11ea-9474-646e69a80395/gazebo_gui-4.log].
log file: /home/kushagra/.ros/log/2f743e76-e7c4-11ea-9474-646e69a80395/gazebo_gui-4*.log
`

**Comment by Jaeyoung-Lim** [comment]
@Kush0301 This is expected, since iris.world doesnt exisr
