### ISSUE TITLE
CI sever needs some new packages

### ISSUE THREAD

**Issue by jgoppert** [PX4/PX4-SITL_gazebo-classic#63]
http://sitl01.dronetest.io/job/PX4%20Firmware%20POSIX%20SITL%20PRs/3050/console

```bash
-- GIT_TAG = v1.5.0-745-gacb48de
-- Configuring incomplete, errors occurred!
See also "/job/catkin/build/CMakeFiles/CMakeOutput.log".
See also "/job/catkin/build/CMakeFiles/CMakeError.log".
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GSTREAMER_LIBRARIES (ADVANCED)
    linked by target "gazebo_geotagged_images_plugin" in directory /job/catkin/src/mavlink_sitl_gazebo
    linked by target "gazebo_gst_camera_plugin" in directory /job/catkin/src/mavlink_sitl_gazebo
    linked by target "rotors_gazebo_gimbal_controller_plugin" in directory /job/catkin/src/mavlink_sitl_gazebo
    linked by target "mav_msgs" in directory /job/catkin/src/mavlink_sitl_gazebo
    linked by target "rotors_gazebo_wind_plugin" in directory /job/catkin/src/mavlink_sitl_gazebo
    linked by target "rotors_gazebo_imu_plugin" in directory /job/catkin/src/mavlink_sitl_gazebo
    linked by target "rotors_gazebo_mavlink_interface" in directory /job/catkin/src/mavlink_sitl_gazebo
    linked by target "rotors_gazebo_controller_interface" in directory /job/catkin/src/mavlink_sitl_gazebo
    linked by target "gazebo_opticalFlow_plugin" in directory /job/catkin/src/mavlink_sitl_gazebo
    linked by target "rotors_gazebo_motor_model" in directory /job/catkin/src/mavlink_sitl_gazebo
    linked by target "LiftDragPlugin" in directory /job/catkin/src/mavlink_sitl_gazebo
    linked by target "gazebo_lidar_plugin" in directory /job/catkin/src/mavlink_sitl_gazebo
    linked by target "rotors_gazebo_multirotor_base_plugin" in directory /job/catkin/src/mavlink_sitl_gazebo
```

@dagar

**Comment by dagar** [comment]
FYI this is running within https://hub.docker.com/r/px4io/px4-dev-ros/ which is defined here - https://github.com/PX4/containers/blob/master/docker/px4-dev/DockerfileRos

I'll start with just gstreamer-base-1.0, unless you happen to know the exact dependencies. There are a lot of gstreamer packages...

**Comment by dagar** [comment]
I added the packages, fixed px4io/px4-dev-ros, and may have broken all of our SITL tests in the process. 
Due to a ppa change px4io/px4-dev-ros had stopped building successfully ~6 months ago.
Standby...

**Comment by jgoppert** [comment]
@dagar OK, great, was actually trying to build it locally as we speak

**Comment by dagar** [comment]
FYI The last working ROS docker image was restored and tagged on Jenkins for now. I'm updating all the images (https://github.com/PX4/containers/tree/master/docker/px4-dev) to extend a common PX4 base, which will bring px4-dev-ros to 16.04 and newer ROS in the process.

**Comment by LorenzMeier** [comment]
Jenkins is currently not reporting any status - is this related?

**Comment by LorenzMeier** [comment]
@AndreasAntener FYI

**Comment by AndreasAntener** [comment]
This should not be related

**Comment by dagar** [comment]
@jgoppert what would you like to do here?
Do you want to try the latest px4-dev-ros and get it working with your testing? https://hub.docker.com/r/px4io/px4-dev-ros/

Last I heard the ros based mission tests (http://sitl01.dronetest.io/job/PX4%20Firmware%20POSIX%20SITL%20PRs/) still only worked reliably with the ROS container built ~ 7 months ago.

**Comment by dagar** [comment]
px4-dev-simulation (gazebo, jmavsim) and px4-dev-ros (simulation + ROS) have gstreamer now. https://github.com/PX4/containers/blob/master/docker/px4-dev/Dockerfile_simulation#L14

Our testing still needs to be updated to use the new environments.
