### ISSUE TITLE
geotagging plugin not working

### ISSUE THREAD

**Issue by igorsgcampos** [PX4/PX4-SITL_gazebo-classic#638]
I am trying to use PX4 SITL to validate an enhancement for survey missions, but I need to have the images geotagged, unfortunately, they are coming without it.

I tried to use the log file and the images but it didn’t work either.

I noticed that the instructions that mention geotagged images refer to the plane_cam model, but the typhoon_h480 (which I am using) uses the same plugin:

```
<plugin name="GeotaggedImagesPlugin" filename="libgazebo_geotagged_images_plugin.so">
    <robotNamespace>typhoon_h480</robotNamespace>
    <interval>1</interval>
    <width>3840</width>
    <height>2160</height>
    <maximum_zoom>8.0</maximum_zoom>
</plugin>
```

I would deeply appreciate if someone could help me to get this working. I plan to run the geotagged images of mcmillan airfield with different parameters on a photogrammetry software and compare the results, hence the use of SITL, it gives me an 100% controlled environment to evaluate the performance differences.

**Comment by igorsgcampos** [comment]
There is a warning, but I think it is not related to it:

[Wrn] [Publisher.cc:185] Queue limit reached for topic /gazebo/default/user_camera/pose, deleting message. This warning is printed only once.

**Comment by igorsgcampos** [comment]
I tried with both the PX4 recommended version of sitl_gazebo and the latest master of this submodule. I am running it with the following command:

make px4_sitl gazebo_typhoon_h480__mcmillan_airfield

**Comment by Jaeyoung-Lim** [comment]
@igorsgcampos The geotagging should be working. Are you sure you have exif tools installed? ( as written in the readme)
```
sudo apt-get install libimage-exiftool-perl
```

**Comment by igorsgcampos** [comment]
Yes, they are properly installed. All dependencies listed in the readme are.

**Comment by Jaeyoung-Lim** [comment]
@igorsgcampos What does https://github.com/PX4/sitl_gazebo/blob/9f832e596a9aaee724d2fce9859e473624e3f87e/src/gazebo_geotagged_images_plugin.cpp#L230 return?

**Comment by igorsgcampos** [comment]
the messages around the image capture messages are as follows:

```
[Dbg] [gazebo_geotagged_images_plugin.cpp:478] Handle Start Capture
[Msg] Took picture: frames/DSC00001.jpg
[Dbg] [gazebo_geotagged_images_plugin.cpp:271] Done with image capture
[Dbg] [gazebo_geotagged_images_plugin.cpp:704] Send capture status
    1 image files updated
```

**Comment by igorsgcampos** [comment]
These are the messages around the image captures:

```
[Dbg] [gazebo_geotagged_images_plugin.cpp:478] Handle Start Capture
[Msg] Took picture: frames/DSC00011.jpg
[Dbg] [gazebo_geotagged_images_plugin.cpp:271] Done with image capture
[Dbg] [gazebo_geotagged_images_plugin.cpp:704] Send capture status
    1 image files updated
```

So it is not returning -1.

When I open the image properties, this is what I get:
![image](https://user-images.githubusercontent.com/22230664/97037474-534ef480-1537-11eb-8cdc-a9de388cda3d.png)

**Comment by igorsgcampos** [comment]
I did some further investigation on my own, it seems that the image is being geotagged, but without coordinates.

The gps topic is being published, it works normally if I subscribe to it with: 
`gz topic -e /gazebo/default/typhoon_h480/gps/link/gps`

I also uncommented and fixed the following line:
`gzdbg << "got gps pos: " << _lastGpsPosition.X() << ", " << _lastGpsPosition.Y() <<endl;`
in: 
`GeotaggedImagesPlugin::OnNewGpsPosition`

but it never enters the scope of this function.

I tried messing up with the subscription command, replacing `/gps` for `/gps/link/gps`, which caused a Segmentation fault, the reason was that if finally entered `GeotaggedImagesPlugin::OnNewGpsPosition`, but the gps_msg was null, causing a null pointer dereference, but it is always null and I haven't found what to do about it yet.

**Comment by igorsgcampos** [comment]
Found the issue: the publisher appends a /link/ to the topic before gps, but the subscriber wasn't appending it, so it wasn't being called. What I couldn't figure out is why I could echo the topic with `gz topic -e /gazebo/default/typhoon_h480/gps/link/gps`, but couldn't with `gz topic -e /gazebo/default/typhoon_h480/link/gps`

https://github.com/PX4/sitl_gazebo/blob/9f832e596a9aaee724d2fce9859e473624e3f87e/src/gazebo_gps_plugin.cpp#L219

https://github.com/PX4/sitl_gazebo/blob/9f832e596a9aaee724d2fce9859e473624e3f87e/src/gazebo_geotagged_images_plugin.cpp#L144
