### ISSUE TITLE
Cannot use UAV motor test command

### ISSUE THREAD

**Issue by leocencetti** [PX4/PX4-SITL_gazebo-classic#639]
Sending the MAVLINK command `MAV_CMD_DO_MOTOR_TEST` with  `id=209`  results in the following warning:
```
[ WARN] [1603312628.991594762, 48.276000000]: CMD: Unexpected command 209, result 3
```
Reproducible using QGroundControl's Motor Setup function.

Full log here: https://pastebin.com/kt44QzNS

**Comment by Jaeyoung-Lim** [comment]
@leocencetti Is this regarding SITL? or PX4 in general?

I don't think the motor test command is supposed to work in SITL Gazebo

**Comment by leocencetti** [comment]
> @leocencetti Is this regarding SITL? or PX4 in general?

It is regarding SITL only.

> I don't think the motor test command is supposed to work in SITL Gazebo

That was my conclusion as well... do you know if is there any other way to mimic the same behavior (one motor spinning at the time)?

**Comment by Jaeyoung-Lim** [comment]
@leocencetti What are you trying to achieve?

If you are interested in adding the functionality, contributions are welcome :smile:

**Comment by leocencetti** [comment]
> @leocencetti What are you trying to achieve?

We are developing a custom calibration routine that requires each motor to spin at a certain speed for a given time (we want to validate it in SITL before deploying on hardware). `motor_test` seemed a good starting point, although I know that the test time is not customizable.

> If you are interested in adding the functionality, contributions are welcome

:wink:

**Comment by Jaeyoung-Lim** [comment]
@leocencetti Would you be able to move this forward?

**Comment by leocencetti** [comment]
> @leocencetti Would you be able to move this forward?

@Jaeyoung-Lim unfortunately no, not in a reasonable time frame.

**Comment by Jaeyoung-Lim** [comment]
@leocencetti Okay, closing then
