### ISSUE TITLE
mavlink_interface compile warning, possible bug?

### ISSUE THREAD

**Issue by George-avy** [PX4/PX4-SITL_gazebo-classic#645]
Hello everyone!

When I'm compiling the mavlink_interface object, I get an error for this line:
https://github.com/PX4/PX4-SITL_gazebo/blob/06e801fe8b5267e561f00d8847a6343cb2386ab6/src/mavlink_interface.cpp#L433-L439

The error message is:
```
<project_dir>/src/mavlink_interface.cpp: In member function ‘void MavlinkInterface::send_mavlink_message(const mavlink_message_t*)’:
<project_dir>/src/mavlink_interface.cpp:513:21: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
  439 |             if (len < 0)
      |                 ~~~~^~~
```
Should < be == perhaps? What is the error result of the preceding `send` function?

**Comment by dagar** [comment]
Both send and sendto return a ssize_t, so we need to fix `len`.

**Comment by dagar** [comment]
https://github.com/PX4/PX4-SITL_gazebo/pull/646
