### ISSUE TITLE
Real time factor is only 0.6 when the usage of CPU and GPU is not great

### ISSUE THREAD

**Issue by robin-shaun** [PX4/PX4-SITL_gazebo-classic#648]
Hello, as I know, Gazebo did computation mainly with only one CPU core in the past. However, when I use Gazebo 9.15, I'm glad to see that all CPU cores are used equally. However, for large scale simulation (30 UAVs), the real time factor is only 0.6 when the usage of CPU and GPU is not great. I don't know why.
![86468385](https://user-images.githubusercontent.com/20561850/97838264-c8ca7a00-1d1a-11eb-85fb-9d3dab547097.jpg)
![904024871](https://user-images.githubusercontent.com/20561850/97838274-cc5e0100-1d1a-11eb-83d6-2c5432db15b7.jpg)

**Comment by bperseghetti** [comment]
The ODE solver needs to be allowed to create threads for each new "robot". My branch pr-hitl-capable-jinja has jinja world files that show what that would look like.

**Comment by Jaeyoung-Lim** [comment]
@robin-shaun With lockstep, I believe your computer is not able to run 30 px4 instances in parallel in realtime with the gazebo simulation. You can try turning off lockstep and see if it helps. On my powerful desktop this is not the case
