### ISSUE TITLE
Wind and Gust setting in gazebo

### ISSUE THREAD

**Issue by moreba1** [PX4/PX4-SITL_gazebo-classic#661]
Hi

I will setup wind gust. 
1- what is the definition of wind gust duration and start? 

windGustDuration>0</windGustDuration
windGustStart>0</windGustStart

https://github.com/PX4/PX4-SITL_gazebo/blob/master/worlds/windy.world#L15-L26

2- I set wind speed 5 m/s but in simulation, wind speed is 1 m/s. why?

**Comment by Jaeyoung-Lim** [comment]
@moreba1 It is the time when the wind gust start and how long the duration is: https://github.com/PX4/PX4-SITL_gazebo/blob/19981d61cfe656d2985fef5285b4a4d14f3be199/src/gazebo_wind_plugin.cpp#L73
