### ISSUE TITLE
Feature Request: Add current waypoint for PX4 SITL/ Transmit current waypoint to QGC

### ISSUE THREAD

**Issue by UASOP** [PX4/PX4-SITL_gazebo-classic#667]
What problem does it solve?
    The current state is that PX4 SITL aircraft does not have the current waypoint option available when connected to QGC, this is helpful when monitoring SITL flights that are used for doing a test run of a flight plan or training students on an airframe that is using PX4 as they will want to know which waypoint the aircraft is heading to in case there is a high degree of overlap in the waypoints, such as in a survey grid mission test plan for a large area with close paths and a large area. There are other examples where this feature would be useful as well.

    What does it do?
    The feature would allow mavlink messages that are communicated from PX4 SITL to QGC to enable the updating of current waypoints in QGC.

    Relevant vehicle types? (All, multirotor, fixed-wing, VTOL, submarine, etc.)
    All vehicle types.

    What communication/integration standards does the feature rely on (e.g. MAVLink commands etc.)
    From my basic understanding, I believe this would need to include a mavlink message for updating QGC on what waypoint the SITL aircraft is going to.

![current WP not available with sitl](https://user-images.githubusercontent.com/7632844/101651985-e6b28b00-39fa-11eb-9271-17170b9e8237.png)

Please let me know if there is any other information needed, Thanks in advance! :)

**Comment by Jaeyoung-Lim** [comment]
@UASOP That looks like a feature request for QGC?
