### ISSUE TITLE
Typhoon H480 Oscillation 

### ISSUE THREAD

**Issue by imcnanie** [PX4/PX4-SITL_gazebo-classic#67]
As soon as I remove the legs from the Typhoon H480 sdf model, the simulation oscillates a lot more. Here's a before and after:

Legs:
![out2](https://cloud.githubusercontent.com/assets/4652417/21248227/66617a28-c2ea-11e6-8fda-df592be4d26b.gif)

No Legs:
![out](https://cloud.githubusercontent.com/assets/4652417/21248180/f386f208-c2e9-11e6-8ef9-f2e83f035350.gif)

SDF for reference:
[hexa.sdf.txt](https://github.com/PX4/sitl_gazebo/files/656201/hexa.sdf.txt)

Any idea why? I'm using the Typhoon as the base for my hexacopter, but mine doesn't have legs or a gimbal. Thank you!

**Comment by imcnanie** [comment]
Actually, increased the mass of the copter to account for the loss of weight and got a different oscillation (makes sense). Should I retune? Or are there other properties to watch for? EDIT: messed around with parameters, started following this guide: http://px4.io/docs/multicopter-pid-tuning-guide/. All my gains are 0 except MC_PITCHRATE_P and MC_ROLLRATE_P which are 0.02 and it flies perfectly, which I doubt is realistic. I want to attempt to tune the simulated version and put those tunes on my real copter.

**Comment by nicolaerosia** [comment]
Just wondering if you figured this one out

**Comment by imcnanie** [comment]
Yes, it looks like the SDF (in Tools/sitl_gazebo/models/typhoon_h480/typhoon_h480.sdf) defined the camera and legs as fairly heavy objects, so when I removed them, the extra weight changed the tune. You can fix this by adding the lost weight to the rest of the model (in the sdf) or changing the PIDs.
