### ISSUE TITLE
standard VTOL model scaling incorrect for body and flaps

### ISSUE THREAD

**Issue by jgoppert** [PX4/PX4-SITL_gazebo-classic#68]
The scaling for the vtol props and frame etc are correct, but when running on gazebo 7 in a catkin workspace, the scaling for the body and flaps is wrong, they are about 100 times larger than they should be.

![vtol-body](https://cloud.githubusercontent.com/assets/473772/21343164/75a30516-c663-11e6-857e-9e61e76f292e.png)

```bash
./integrations_tests/run_tests.bash
```

let it run, and it will create a catkin workspace on the parent directory of the px4 source, now navigate to that directory

```
cd ../catkin
. ./devel/setup.bash
catking build
rostest px4 mavros_posix_tests_standard_vtol.launch gui:=true
```

**Comment by TSC21** [comment]
I think this is solved already. Closing
