### ISSUE TITLE
Use sdf files in rviz

### ISSUE THREAD

**Issue by AliaChe** [PX4/PX4-SITL_gazebo-classic#693]
Hello, 

I'm trying to use rviz to visualize a simulated iris drone in gazebo. Since the urdf and xacro files are deprecated, is there any method to visualize the drone, TF and the lazerscans in rviz using the sdf files instead of the urdf files? 

Thank you.

**Comment by Jaeyoung-Lim** [comment]
@AliaChe You can define markers that can be visualized in Rviz: http://wiki.ros.org/rviz/DisplayTypes/Marker

**Comment by AliaChe** [comment]
@Jaeyoung-Lim Thank you for your reply,  do you have any concrete example where markers are used to visualize the drone, the lidar and the lazerscans?

**Comment by Jaeyoung-Lim** [comment]
@AliaChe You can check how this is being done in the [PX4/Avoidance](https://github.com/PX4/PX4-Avoidance) project.
