### ISSUE TITLE
BlueROV2 Thruster chaotic Movement

### ISSUE THREAD

**Issue by timzarhansen** [PX4/PX4-SITL_gazebo-classic#694]
Does someone know the reason why the propeller/thruster are moving around in the simulation if the motors are actuated?
This happens in Gazebo 11 started with:
`make px4_sitl_default gazebo_uuv_bluerov2_heavy`
If the motors are not actuated they are at the correct position. 

![Screenshot from 2021-01-19 11-40-00](https://user-images.githubusercontent.com/10078972/105023644-81b37180-5a4b-11eb-9f76-64dba8fe50f3.png)

**Comment by Jaeyoung-Lim** [comment]
@lennartalff Would it be possible for you to have a look?

**Comment by lennartalff** [comment]
Should be solved in PX4/PX4-Autopilot#16637. If the Problem still occurs, please let me know.

**Comment by Jaeyoung-Lim** [comment]
@lennartalff I have just tried and the problem is not solved.

@Zarbokk Was https://github.com/PX4/PX4-SITL_gazebo/pull/696 related to fixing this issue?

I first thought it was related to a sdf format issue, but I can't find out why anymore

**Comment by timzarhansen** [comment]
Currently, I was not able to solve that problem.
The direction of the propeller is exactly the direction of the force that is acting on the body/propeller.
It behaves like a spring, Big force Big movement, low force low movement.
In the Gazebo forum, I was not able to find something useful only small related problems, without a real solution.

Maybe it's related to the Gazebo version? I am currently using Gazebo 11.

**Comment by lennartalff** [comment]
@Jaeyoung-Lim I think it is related to the solver settings. Increasing the `<iters>` value in `uuv_bluerov2_heavy.world` to at least 20 reduces the errenous deflection of the rotors. Is there a reason for the chosen value of 10? Otherwise I would propose to increase it to 20 or maybe even use the default value of 50?
@Zarbokk Maybe you want to check if #701 solves the problem for you?

**Comment by timzarhansen** [comment]
solved by hub.com/PX4/PX4-SITL_gazebo/pull/701
