### ISSUE TITLE
Gazebo not linking with MAVROS

### ISSUE THREAD

**Issue by RotorBoy2020** [PX4/PX4-SITL_gazebo-classic#695]
Hello, 

I have been following the documentation for using MAVROS with Gazebo found here: https://docs.px4.io/master/en/simulation/ros_interface.html 

My problem is 1.) `make px4_sitl_default gazebo` fails, and 2.) because `make px4_sitl_default gazebo` fails, I cannot seem to link MAVROS with Gazebo. 

Problem 1: `make px4_sitl_default gazebo`
When I run this command, the code gets built to 100%, I see the PX4 logo, and then when gazebo starts I see the following output:

```
INFO  [dataman] Unknown restart, data manager file './dataman' size is 11798680 bytes
INFO  [simulator] Waiting for simulator to accept connection on TCP port 4560
Gazebo multi-robot simulator, version 9.0.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: <my-ip-address>
[Err] [ModelDatabase.cc:390] Unable to parse model.config for model[http://gazebosim.org/models/bin_4_dropping_task]
```
which leads me to believe that gazebo is not starting properly. Also, the code works if I use the `DONT_RUN=1` like the docs suggest, but that's just because I don't open gazebo. 

Problem 2: Gazebo not linking with MAVROS
After I run `roslaunch px4 posix_sitl.launch`, Gazebo loads and I can see all the MAVROS and gazebo topics. However after viewing rqt_graph I can see that none of the MAVROS and gazebo topics are talking to each other. If I ping /mavros/imu/data it does not update, and /mavros/state shows it is not connected. I think this is related to problem 1. 

System:
Jetson Nano
Ubuntu 18.04
ROS Melodic 
Installed PX4-Autopilot folder yesterday 
Gazebo 9.0.0
PX4 

Any help would be greatly appreciated! Thank you

**Comment by Jaeyoung-Lim** [comment]
@RotorBoy2020 For problem 1) if you wait long enough, it should eventually run. I am not sure why your gazebo is trying to download stuff from the model server, but that looks like it is trying to do exactly that.

For problem 2), seems like it is coupled with 1) You just can't run PX4 SITL at all.

Where are you running this? Is this on a Ubuntu host system? or a VM?

**Comment by RotorBoy2020** [comment]
Hello @Jaeyoung-Lim ! Thank you for your reply. 

For 1) After running `roslaunch px4 mavros_posix_sitl.launch` I waited for 15 minutes and MAVROS was still showing that it was not connected. 

For 2) yes I agree, they are certainly coupled. 

I am only developing with my Jetson Nano with Ubuntu 18.04.  Yesterday, after my post, I successfully [ran a couple of gazebo tutorials](https://www.youtube.com/watch?v=qi2A32WgRqI&list=PLK0b4e05LnzbHiGDGTgE_FIWpOCvndtYx&index=1) to make sure that gazebo could run a bare model. On my Jetson Nano, I have written python code with MAVROS to fly the drone in a small loop with a mRo Pixhawk and that worked fine, so the basic download of MAVROS is working well. It seems the issue is entirely gazebo related. 

Any ideas?

**Comment by Jaeyoung-Lim** [comment]
Ah, if it is the jetson nano, can you even just run gazebo?

**Comment by RotorBoy2020** [comment]
Yes I can run gazebo, I followed a couple of tutorials and that worked as expected. At one point I had turtlebot3 running on gazebo

**Comment by Jaeyoung-Lim** [comment]
Okay, then I am not sure what the issue is. Running SITL in gazebo on a Jetson nano is not a supported use case(It has it's own Ubuntu distribution), so if you can find out what went wrong, that would be great

**Comment by RotorBoy2020** [comment]
Ok, for the mean time I switched to my laptop and Gazebo has been working as expected. Thank you for your help, if I find anything else useful on getting it to run on the Nano I'll post my findings.

Thank you!
