### ISSUE TITLE
thermal camera model (.sdf file) 

### ISSUE THREAD

**Issue by addy1997** [PX4/PX4-SITL_gazebo-classic#706]
I am trying to integrate a thermal camera with my IRIS quadcopter and simulate it in the ignition gazebo with PX4. If this feature is not possible, can you guide me on how to implement the file?

**Comment by Jaeyoung-Lim** [comment]
@addy1997 There are two big questions in your question.

1. Using ignition gazebo is not implemented in this repository. You will need to port part the implementation of this repo into ignition gazebo. Classical "gazebo" and "ignition gazebo" are not compatible with different architecture and API

2. For thermal cameras, you need to add a "thermal camera" plugin. For reference, you can look at something like: http://wiki.ros.org/hector_gazebo_thermal_camera

**Comment by addy1997** [comment]
But porting requires permission from the repo owner right? I just can't take away a chunk of code.

**Comment by Jaeyoung-Lim** [comment]
@addy1997 As long as you comply with the license of this repository, there is nothing preventing you from doing so

**Comment by addy1997** [comment]
Indubitably, yes I will comply. @Jaeyoung-Lim thanks for your help. really appreciated !!!
