### ISSUE TITLE
Plane airspeed failure on landing

### ISSUE THREAD

**Issue by ghfue** [PX4/PX4-SITL_gazebo-classic#713]
When the plane model lands, the following warning is given:
```WARN [airspeed_selector] Airspeed sensor failure detected (1, -1)```.

The airspeed is then considered invalid, causing it to fail the pre-arm checks.
```WARN [PreFlightCheck] Preflight fail: Airspeed invalid.```

This means to refly a mission or to fly multiple missions after landing, the PX4 sim has to be restarted.

**Comment by Jaeyoung-Lim** [comment]
@ghfue Do you have a log? wondering what is happening to the airspeed sensor

**Comment by ghfue** [comment]
[Log](https://logs.px4.io/plot_app?log=513574fe-35c7-49bb-b5ad-0a12441df5dc)

**Comment by dayjaby** [comment]
Got that error on a real drone (with PX4 1.12.1) as well, so might not be related to simulations.

**Comment by T3chDad** [comment]
I've had this problem too.  ZOHD Dart XL with the pitot tube on the left wing the airspeed sensor fails on every single landing and requires a power off to reset.  v1.12.3 on MRO Control Zero H7 FC.

**Comment by Jaeyoung-Lim** [comment]
@T3chDad @dayjaby Thanks for the update Would you be able to post a issue with the log on the upstream repository?

If you also see this on a real vehicle, I don't think this issue is related to the simulation.

**Comment by T3chDad** [comment]
Here is the [log of my last flight yesterday](https://logs.px4.io/plot_app?log=5eecad1b-9c56-4d50-b5b8-437baa2230d4).  Airspeed failed on landing.  This was the third flight of this aircraft.  All three flights ended with an easy landing and airspeed sensor failure.

**Comment by Jaeyoung-Lim** [comment]
@T3chDad Please post the issue on https://github.com/PX4/PX4-Autopilot/issues with details of your setup and failures

**Comment by T3chDad** [comment]
> @T3chDad Please post the issue on https://github.com/PX4/PX4-Autopilot/issues with details of your setup and failures

**Done!**

**Comment by sfuhrer** [comment]
@ghfue the PX4 version you fly with doesn't have this fix: https://github.com/PX4/PX4-Autopilot/pull/17051
During landing, the airspeed drops below stall speed (ASPD_STALL), causing the trigger.
It will be further improved by https://github.com/PX4/PX4-Autopilot/pull/18442, which by default disables the failure detection based on stall speed.

**Comment by ghfue** [comment]
@sfuhrer Current tests on master show the same failure behavior. I tested with [PX4/PX4-Autopilot#18442](https://github.com/PX4/PX4-Autopilot/pull/18442), and it resolved the issue. I'll close this when the PR lands.

**Comment by rrajnidhi** [comment]
Even i was facing same issue. I guess the reason was bcz of steady airspeed sensor value getting published after landing or when aircraft is not moving. PX4 considers this as a sensor fault. I have resolved it by changing the value of wait time from 1 second to 10second in /src/modules/airspeed_selector/airspeed_selector_main.cpp Try and let me know.

**Comment by rrajnidhi** [comment]
> Got that error on a real drone (with PX4 1.12.1) as well, so might not be related to simulations.

Correct, Its not with simulation.

**Comment by Jaeyoung-Lim** [comment]
@rrajnidhi Are you sure your firmware includes https://github.com/PX4/PX4-Autopilot/pull/18442 ? (Repeated comments from https://github.com/Auterion/px4-jsbsim-bridge/issues/49)
