### ISSUE TITLE
Controlling the gimbal on typhoon-h480

### ISSUE THREAD

**Issue by nilesh-aggarwal** [PX4/PX4-SITL_gazebo-classic#720]
Hi, I need the gimbal on typhoon-h480 to point downwards. I followed this (https://docs.px4.io/master/en/advanced/gimbal_control.html) and decided on sending mavlink messages using .plan files on qgroundcontrol. But the drone did not respond to those commands. 
Can someone help me figure out how to  make the gamera on typhoon-h480 downfacing?

**Comment by Jaeyoung-Lim** [comment]
@nilesh-aggarwal Any chance you have seen https://github.com/Jaeyoung-Lim/mavros_humantracking ?
