### ISSUE TITLE
upgrade the msgs from 'proto2' to 'proto3'

### ISSUE THREAD

**Issue by addy1997** [PX4/PX4-SITL_gazebo-classic#744]
For my project, I need to upgrade the [msgs](https://github.com/PX4/PX4-SITL_gazebo/blob/master/msgs/Imu.proto) from proto2 to proto3. Is changing the syntax enough?

**Comment by Jaeyoung-Lim** [comment]
@addy1997 I think whether if it is enough or not will depend on your project? Does this answer your question?

**Comment by addy1997** [comment]
> @addy1997 I think whether if it is enough or not will depend on your project? Does this answer your question?

Sorry, I should have included more details. So, I am replicating the model of [this project](https://github.com/utiasSTARS/PhoenixDrone-sitl_gazebo) for my [project](https://github.com/addy1997/AlphaDrone-SITL_ignition-gazebo) based on `AlphaDrone` with `Ignition gazebo` that supports `protobuf 3`. To put it into perspective, I am creating my own message packages based on `protobuff3`. Are these details enough?

**Comment by Jaeyoung-Lim** [comment]
@addy1997 I am not sure. Did you have any issues when updating?

**Comment by addy1997** [comment]
> @addy1997 I am not sure. Did you have any issues when updating?

@Jaeyoung-Lim, thanks for your help.
