### ISSUE TITLE
SITL_Gazebo plugins vs.  Gazebo_Ros plugins 

### ISSUE THREAD

**Issue by doman93** [PX4/PX4-SITL_gazebo-classic#746]
I would like to integrate a kinect (or a depth camera like Realsense) on the model Iris of SITL_Gazebo. However, there is no available specific plugin developed by PX4 team for that purpose (or we need to combine many plugins). 
On the other hand, it noticed that "gazebo-ros-pkgs" offers and supports officially the plugin "libgazebo_ros_openni_kinect.so ", so can i add it directly to model "iris.sdf" of sitl_gazebo?
Ps: sorry if i made stupid questions, since i just start to learn about ros, gazebo and px4 simulation.

**Comment by TSC21** [comment]
We have the a depth camera model with that plugin that can be included in any vehicle SDF: https://github.com/PX4/PX4-SITL_gazebo/blob/master/models/depth_camera/depth_camera.sdf.jinja. note that the jinja file is for the model generarion. Only after the build process, the .sdf gets generated.

**Comment by doman93** [comment]
> We have the a depth camera model with that plugin that can be included in any vehicle SDF: https://github.com/PX4/PX4-SITL_gazebo/blob/master/models/depth_camera/depth_camera.sdf.jinja. note that the jinja file is for the model generarion. Only after the build process, the .sdf gets generated.

If I renamed the extension .sdf.jinja  -> .sdf , the model "Intel Realsense " should still work i believe, then I have to add the corresponding model description to world file. In fact, I have to work on an old version of SITL_gazebo so I cannot rebuild everything with the latest Cmakelist

**Comment by TSC21** [comment]
No it doesn't work. Please check the file. You will see there are some conditionals there dependent on jinja code. You will have to remove the part that doesn't matter to you (which would be the one dependent on ROS2).

**Comment by doman93** [comment]
> You will have to remove the part that doesn't matter to you (which would be the one dependent on ROS2).

I saw you made {% if ros_version == 2 %} and {%else%}. I didn't notice that, thanks @TSC21 .  Basically, px4 team made a model work for both ROS 1 and 2 versions but its final version will be generated later after build process. The plugin will also change based on ROS version if I am not wrong.

**Comment by TSC21** [comment]
> > You will have to remove the part that doesn't matter to you (which would be the one dependent on ROS2).
> 
> I saw you made {% if ros_version == 2 %} and {%else%}. I didn't notice that, thanks @TSC21 . Basically, px4 team made a model work for both ROS 1 and 2 versions but its final version will be generated later after build process. The plugin will also change based on ROS version if I am not wrong.

Yes.
