### ISSUE TITLE
Cannot see the model when using "make px4_sitl_default gazebo_iris__windy"

### ISSUE THREAD

**Issue by AllenHuangSpeedy** [PX4/PX4-SITL_gazebo-classic#763]
Hi,

I am facing a problem when I want to put iris in a specific world following the turtorial. When I was trying to use different world, the model doesn't show up. This problem confused me for weeks, hope someone can help me. 

Besides, I want to use my own model into SITL, but I don't know where I can define the property of model like iris for using the "make px4_sitl_default gazebo_xxx".

Many thanks!
Allen

**Comment by Jaeyoung-Lim** [comment]
@AllenHuangDongyue 

The correct target should be
```
make px4_sitl gazebo_iris__windy
```
