### ISSUE TITLE
qusetion about  acceleration control

### ISSUE THREAD

**Issue by 958117216** [PX4/PX4-SITL_gazebo-classic#764]
Hi,I have some problems and hope to get your help.

To make the drone fly at the desire acceleration,my thought is make the drone at a  specified altitude and attitude.

For example, I tilt 5 degrees to produce acceleration of tan (5°)* g, but in the px4 gazebo simulation, it can only reach a certain speed and the acceleration is 0.Is there any resistance here I overlooked? Have you encountered this situation in simulation? Thanks and look forward to your reply.

**Comment by Jaeyoung-Lim** [comment]
@958117216 Since the rotors have drag, your tilt angle does not necessarily result in acceleration. The vehicle will just reach the velocity in which the forward force and the drags are the same magnitude (also called as terminal velocity)

**Comment by 958117216** [comment]
@Jaeyoung-Lim  Thank you very much for your reply. 
How is the rotor drag calculated in gazebo? Is the following line of code? 
air_drag = -std::abs(real_motor_velocity) * rotor_drag_coefficient_ * body_velocity_perpendicular;


I just think the acceleration caused by tilt in the simulation is much smaller than the actual one.

**Comment by Jaeyoung-Lim** [comment]
> I just think the acceleration caused by tilt in the simulation is much smaller than the actual one.

@958117216 I don't think this statement is necessarily true. This will depend on which airframe you are talking about, which is defined by several parameters. If you define your parameters close enough to your platform of interest the model in this repo behaves quite similarly with the real model except when you are doing extremely aggressive maneuvers. 

> How is the rotor drag calculated in gazebo? Is the following line of code?
> air_drag = -std::abs(real_motor_velocity) * rotor_drag_coefficient_ * body_velocity_perpendicular;

https://github.com/PX4/PX4-SITL_gazebo/blob/5c248898524cb670df496149de5e4692e16e69dc/src/gazebo_motor_model.cpp#L231

**Comment by 958117216** [comment]
@Jaeyoung-Lim  Thank you very much.
