### ISSUE TITLE
Missing pxh> on terminal command when launching multi_uav_mavros_sitl.launch

### ISSUE THREAD

**Issue by JethroPhuah** [PX4/PX4-SITL_gazebo-classic#773]
Hi, 

Previously, I followed the tutorial online https://docs.px4.io/master/en/modules/hello_sky.html to launch a simple application. On the tutorial, I am able to run the application by hitting <ENTER> and seeing the pxh> on the terminal screen. However, I wanted to try it on a multi uav simulation. This is my launch file for your reference. 

cd ./PX4-Autopilot
DONT_RUN=1 make px4_sitl_default gazebo
source ~/catkin_ws/devel/setup.bash    
source Tools/setup_gazebo.bash $(pwd) $(pwd)/build/px4_sitl_default
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$(pwd)
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$(pwd)/Tools/sitl_gazebo
roslaunch px4 multi_uav_mavros_sitl.launch world:=$(pwd)/../worlds/custom_map.world

However, it seems that when I hit on <ENTER>, pxh> does not appear and I am unable to run my application. May I know if it is possible to add a plugin or something so that I would be able to test my application just like stated in the tutorial above? 

Many thanks in advance!

**Comment by Jaeyoung-Lim** [comment]
@JethroPhuah It is disabled intentionally, since a pxh is a shell for a single vehicle, while when you run multiple vehicles in a launchfile the shell should not belong to any of the vehicles.
