### ISSUE TITLE
Gazebo's world not spawning

### ISSUE THREAD

**Issue by ZhiWei20011** [PX4/PX4-SITL_gazebo-classic#774]
Hi, I tried to download your mcmillan_airfield world file to my workspace and my gazebo is not spawning (it keeps saying waiting for simulation in the terminal) when I called my workspace to launch the mcmillan world. Any suggestions? Thank you.

**Comment by Jaeyoung-Lim** [comment]
@ZhiWei20011 Please provide more details on what you are trying to do.

Could you confirm everything works with the standard setup?
(e.g. `make px4_sitl gazebo_iris__mcmillain_airfield`)

**Comment by ZhiWei20011** [comment]
Nope, I am not able to launch it with the standard setup. Any reason why?
![Screenshot from 2021-06-25 17-45-08](https://user-images.githubusercontent.com/85549044/123356160-be0a7100-d599-11eb-8a4b-30876d2e2ff0.png)

**Comment by Jaeyoung-Lim** [comment]
@ZhiWei20011 The command you are running is not supported.

Please follow the documentation to try out this repoistory: http://docs.px4.io/master/en/simulation/gazebo.html
