### ISSUE TITLE
Getting the error "WARN  [cdev] : exceeded maximum number of file descriptors, accessing /obj/follow_target0"

### ISSUE THREAD

**Issue by JethroPhuah** [PX4/PX4-SITL_gazebo-classic#776]
Hi, 

I tried obtaining the gps location of my current vehicle and target vehicle via subscription to the uORB topic vehicle_gps_position and uORB topic target_follow. Thought I am able to obtain the gps location, the terminal displays the error "WARN  [cdev] : exceeded maximum number of file descriptors, accessing /obj/follow_target0" after a few seconds. Attached below is my code:

#define PI 3.14159265358979323846
#define RADIO_TERRESTRE 6372797.56085
#define GRADOS_RADIANES PI / 180

#include <px4_platform_common/px4_config.h>
#include <px4_platform_common/tasks.h>
#include <px4_platform_common/posix.h>

#include <unistd.h>
#include <stdio.h>
#include <poll.h>
#include <string.h>
#include <math.h>
#include <algorithm>
#include <iostream>
#include <uORB/uORB.h>
#include <px4_platform_common/log.h>
#include "FlightTaskFollowYaw.hpp"
#include <uORB/topics/vehicle_gps_position.h>

#include <string.h>
#include <stdlib.h>
#include <stdbool.h>
#include "ecl/mathlib/mathlib.h"
#include <fcntl.h>

#include <systemlib/err.h>

#include <uORB/uORB.h>
#include <uORB/topics/position_setpoint_triplet.h>
#include <uORB/topics/follow_target.h>
#include <lib/ecl/geo/geo.h>
#include <lib/mathlib/math/Limits.hpp>

#include "modules/navigator/navigator.h"

bool FlightTaskFollowYaw::activate(const vehicle_local_position_setpoint_s &last_setpoint){

    std::cout << "Follow Yaw try again5" << std::endl;
    //std::cout << "Sending lat vehicle 1: " << (gps.lat)/10000000 << " lon: "<< (gps.lon)/10000000 << " alt: " << (gps.alt)/10000000 << std::endl;
    //std::cout << "Sending lat vehicle 2: " <<_current_target_motion.lat << " lon: "<<_current_target_motion.lon << " alt: " <<_current_target_motion.alt << std::endl;
    bool ret = FlightTask::activate(last_setpoint);

    // to get local vehicle buffer gps position
    int gps_sub_fd = orb_subscribe(ORB_ID(vehicle_gps_position));
    orb_set_interval(gps_sub_fd, 200);
    orb_copy(ORB_ID(vehicle_gps_position), gps_sub_fd, &gps);

    // to get vehicle 2 buffer gps position
    int follow_target_fd = orb_subscribe(ORB_ID(follow_target));
    orb_set_interval(follow_target_fd, 200);
    orb_copy(ORB_ID(follow_target), follow_target_fd, &ft);

    if (_vehicle1_sub.updated())
    {
        std::cout << "Sending lat vehicle 1: " << (double)(gps.lat)/10000000 << " lon: "<< (double)(gps.lon)/10000000 << " alt: " << (double)(gps.alt)/1000000 << std::endl;
    }
    if (_follow_target_sub.updated())
    {
        std::cout << "Sending lat vehicle 2: " << (ft.lat) << " lon: "<< (ft.lon) << " alt: " << (ft.alt) << std::endl;
    }
    double dist = getDistance((double)(gps.lat)/10000000, (double)(gps.lon)/10000000, (double)(gps.alt)/100000, ft.lat, ft.lon, (double)(ft.alt)/10000000);
    double distance = CalcGPSDistance((double)(gps.lat)/10000000, (double)(gps.lon)/10000000, ft.lat, ft.lon);

    return ret;

}

Any help to prevent this warning from occurring is greatly appreciated!

**Comment by TSC21** [comment]
This issue has nothing to do with this repo. Please move it to https://github.com/PX4/PX4-Autopilot. Thank you!
