### ISSUE TITLE
Questions about implementing a new copter configuration

### ISSUE THREAD

**Issue by imcnanie** [PX4/PX4-SITL_gazebo-classic#78]
I'm planning on implementing a new copter configuration for the sitl_gazebo plugin, I have a few questions about some of the plugin variables:

How are the motorConstant and motorMoment variables calculated? (in the SDF):
https://github.com/PX4/sitl_gazebo/blob/d6c12fb9e68608db2ad56f4ec6c74e5a491e17ee/src/gazebo_motor_model.cpp#L186

Similarly curious about rotorDragCoefficient, and rollingMomentCoefficient. Are these parameters following a paper? Also, curious what unit maxRotVelocity is in.

**Comment by TSC21** [comment]
@imcnanie were you able to get the answers to this?

**Comment by imcnanie** [comment]
Yes! Fantastic! I mostly figured it out, but that's much more comprehensive. We can close this now.

**Comment by ChristophTobler** [comment]
@imcnanie Anything that needs to be documented?

**Comment by TSC21** [comment]
> @imcnanie Anything that needs to be documented?

What needs documentation is #110, which will answer to this. I'm closing this so we can follow up on the other issue. @imcnanie can you leave your finding there, please? Thanks
