### ISSUE TITLE
Support ignition gazebo

### ISSUE THREAD

**Issue by blakermchale** [PX4/PX4-SITL_gazebo-classic#780]
Supporting ignition gazebo would be useful since it's looking like classic gazebo will be replaced inevitably. There's already a migration tutorial for ardupilot [here](https://github.com/ignitionrobotics/ign-gazebo/blob/ign-gazebo5/tutorials/migrating_ardupilot_plugin.md). I'm not sure how difficult this would be or if it would be useful. I do know ignition gazebo has support for separated cloud based simulations and would definitely expand the usability of PX4 across the community.

**Comment by LorenzMeier** [comment]
We have in fact completed a first iteration. @Jaeyoung-Lim what's the current state to make this available to the wider community?

**Comment by Jaeyoung-Lim** [comment]
@LorenzMeier I am coordinating with @markusachtelik in making the repo public! 

Related to https://github.com/PX4/PX4-SITL_gazebo/issues/714

**Comment by Jaeyoung-Lim** [comment]
@blakermchale A little sneakpeak of the current status of the ignition implementation: https://youtu.be/38UJqrNQChg

**Comment by Jaeyoung-Lim** [comment]
Pull request created in https://github.com/PX4/PX4-Autopilot/pull/17889

Therefore, closing this issue
