### ISSUE TITLE
Yosemite world fails to launch in gazebo

### ISSUE THREAD

**Issue by mihirk2309** [PX4/PX4-SITL_gazebo-classic#788]
I am trying to launch gazebo with the Yosemite world. I am using 
`make px4_sitl_default gazebo___yosemite `
command
But Gazebo is stuck at this point and does not open even after waiting for a really long time.
![Screenshot from 2021-07-28 01-20-35](https://user-images.githubusercontent.com/63548541/127218650-7bdb9653-cb2b-44c7-a206-9beac82b7478.png)
For all other worlds like sonoma_raceway or baylands etc. gazebo opens up flawlessly without having to wait for even a few seconds. Can anyone help with this issue?
PS:- I haven't modified the world files of any of the worlds in any way. In fact, I tried cloning the PX4_autopilot as it is multiple times and unfortunately, its the same everytime

**Comment by tfoote** [comment]
If you're only waiting for less than a few seconds for the others you are likely using a cached copy that's local. When the splash screen is loading like that it's fetching the assets for the world. If you see network traffic you may just need to be more patient. The Yosemite world is a lot larger, and may take some time to download depending on your bandwidth availability.

**Comment by mihirk2309** [comment]
I don't think that's the issue. Here's why:
1) I waited for more than 2 hours for it to load but it did not.
2) Network bandwidth is sufficient (200mbps stable)
3) I tried the same after doing `rosclean purge` and cloning a fresh PX4_Autopilot but its still stuck at this point
![Screenshot from 2021-07-28 08-41-14](https://user-images.githubusercontent.com/63548541/127257727-ea2769f7-adb7-4ab4-9cbd-41366691d272.png)

**Comment by Jaeyoung-Lim** [comment]
@mihirk2309 You can try removing your local cache in `~/.gazebo` and enable `VERBOSE_SIM=1` to see more information of what the problem is

I just tried on latest master and it works:
![image](https://user-images.githubusercontent.com/5248102/127306018-025fe199-1a84-421b-8d8c-bbb88e8c5d79.png)

**Comment by mihirk2309** [comment]
Deleting all Yosemite related files from `~/.gazebo` and building again did the job. Thanks a lot, @Jaeyoung-Lim and @tfoote for your help!
