### ISSUE TITLE
Camera not showing images

### ISSUE THREAD

**Issue by saadnec** [PX4/PX4-SITL_gazebo-classic#794]
I embedded  camera in  the iris vehicle by copying the camera code into the iris file but when i retrieve the image messages they continue to show the same matrix or slightly different numbers (same color) and when i visualize the picture using cv2.imshow it keeps showing the same grey color  when my vehicle is moving, i have put objects in my world but camera continues to show the same grey screen. 

I tried two cameras i.e stereo and depth but i faced the same issue in both the cases.
I am launching using roslaunch multi_uav_mavros_sitl to launch my vehicles.

**Comment by Jaeyoung-Lim** [comment]
@saadnec If you have found the solution, please share it with the rest of the community so that they don't need to go through the problem again.
