### ISSUE TITLE
Could not set gimbal plugin with pitch higher tan 90º

### ISSUE THREAD

**Issue by AaronSenra89** [PX4/PX4-SITL_gazebo-classic#795]
Hello,

I recently migrated gazebo px4 simulation environment from 1.11.3 to 1.12.1 to use it with my custom drone.

After some changes I managed to make it work but now i noticed that when I try to set pitch higher 90º or lower -90º it starts to change roll instead of only pitch.

I am using Gimbal plugin like in typhoon_h480 but only with 2 axis, pitch and roll. To command gimbal position I am using the topic /mavros/mount_control/command.

The limits of the pitch joint are:
``
          <lower>-2.4</lower>
          <upper>2.4</upper>
``
Besides I needed to change px4 mnt related configuration to be able to move gimbal, without this it doesn't work
From px4 1.11.3
    MNT_MODE_IN 0
    MNT_MODE_OUT 0
to px4 1.12.1
    MNT_MODE_IN 4
    MNT_MODE_OUT 2

With this last change i lose the topic which i use to check gimbal position, /mavros/mount_control/orientation. Is there another one that i can use?

There is something more in the configuration that is required to change to be able to set pitch higher or lower +-90º?

Thanks in Advance

**Comment by Jaeyoung-Lim** [comment]
@AaronSenra89 You cannot set pitch larger or smaller than the range of [-90, 90] deg.

This is called gimbal lock, and you can find out why i this [article](https://en.wikipedia.org/wiki/Gimbal_lock#:~:text=Gimbal%20lock%20is%20the%20loss,a%20degenerate%20two%2Ddimensional%20space.)
