### ISSUE TITLE
Sitl standard VTOL problem V1.12

### ISSUE THREAD

**Issue by moreba1** [PX4/PX4-SITL_gazebo-classic#799]
Hi

I can not do SITL standard VTOL with version of 1.12.0 to 1.12.3 but I can it with version of 1.11.3 . Gazebo runs but can not connect to QGroundControl. I don't have this problem with multirotor and plane simulation. 

![xxxxxxxxxxxx](https://user-images.githubusercontent.com/14200369/132492182-f192d5f0-e117-4e4c-9786-28da2d5c4b13.png)

**Comment by Jaeyoung-Lim** [comment]
@moreba1 
- I can run the standard VTOL with the latest version of PX4, 
- Standard vtol is being checked as part of the SITL testing automatically in the CI, therefore this would have been detected in the firmware CI but it hasn't.

Therefore, Can you recheck your environment? I am not sure if this is problem in either this repo or the firmware

**Comment by Jaeyoung-Lim** [comment]
@moreba1 Please reopen if this is still an issue. Closing since I didn't get a response.
