### ISSUE TITLE
plane motor issue

### ISSUE THREAD

**Issue by dagar** [PX4/PX4-SITL_gazebo-classic#86]
Something strange happens to the plane model in auto landing at flare. The throttle cuts (in the px4 logs), but the vehicle starts climbing and gets stuck in a flyaway.

![gazebo](https://cloud.githubusercontent.com/assets/84712/22678965/74cd8aa0-eccc-11e6-9f5d-4189ea5d0f13.png)

The only thing noteworthy I saw in the console is this message.

    [Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/default/plane/gazebo/command/motor_speed, deleting message. This warning is printed only once.

http://logs.uaventure.com/view/xaJwxSYbc7jXBN2Xa7Yuii

**Comment by dagar** [comment]
It looks like this is probably coming from the pwm_out_sim in PX4.

**Comment by LorenzMeier** [comment]
Fixed.
