### ISSUE TITLE
GStreamer Camera Plugin - Corrupted Stream

### ISSUE THREAD

**Issue by petergerten** [PX4/PX4-SITL_gazebo-classic#94]
I want to use the gst camera plugin with the Typhoon H480 model.
For some reason I get a corrupted H.264 stream that crashes most decoders I tried. I get however a few correct frames. If I change the pipline in the source code to the testSrc everything works as expected. So it seems there is no problem with the encoder pipeline but somehow wrong data comes from the dataSrc.

Does anyone currently use this plugin successfully or experienced similar issues?

**Comment by TSC21** [comment]
@petergerten please check if latest upstream master solves this. We will reopen if not. Closing.
